create table if not exists public.contractors (
  id bigint generated by default as identity primary key,
  name text not null,
  contact_person text,
  phone text,
  email text,
  city text,
  street text,
  nip text,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null
);

create index if not exists contractors_name_idx on public.contractors (lower(name));
create index if not exists contractors_phone_idx on public.contractors (phone);
create index if not exists contractors_email_idx on public.contractors (lower(email));

alter table public.contractors enable row level security;

drop policy if exists contractors_admin_select on public.contractors;
drop policy if exists contractors_admin_insert on public.contractors;
drop policy if exists contractors_admin_update on public.contractors;
drop policy if exists contractors_admin_delete on public.contractors;

create or replace function public.is_admin_user()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'Administrator'
  );
$$;

create policy contractors_admin_select
on public.contractors
for select
using (public.is_admin_user());

create policy contractors_admin_insert
on public.contractors
for insert
with check (public.is_admin_user());

create policy contractors_admin_update
on public.contractors
for update
using (public.is_admin_user())
with check (public.is_admin_user());

create policy contractors_admin_delete
on public.contractors
for delete
using (public.is_admin_user());

create or replace function public.set_contractors_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists contractors_set_updated_at on public.contractors;
create trigger contractors_set_updated_at
before update on public.contractors
for each row
execute function public.set_contractors_updated_at();

create or replace function public.admin_list_contractors()
returns setof public.contractors
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin_user() then
    raise exception 'Brak uprawnień administratora do modułu kontrahentów.';
  end if;

  return query
  select *
  from public.contractors
  order by lower(name), id desc;
end;
$$;

create or replace function public.admin_upsert_contractor(
  p_id bigint default null,
  p_name text default null,
  p_contact_person text default null,
  p_phone text default null,
  p_email text default null,
  p_city text default null,
  p_street text default null,
  p_nip text default null,
  p_notes text default null,
  p_is_active boolean default true
)
returns public.contractors
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.contractors;
begin
  if not public.is_admin_user() then
    raise exception 'Brak uprawnień administratora do zapisu kontrahenta.';
  end if;

  if nullif(trim(coalesce(p_name, '')), '') is null then
    raise exception 'Pole name jest wymagane.';
  end if;

  if p_id is null then
    insert into public.contractors (
      name,
      contact_person,
      phone,
      email,
      city,
      street,
      nip,
      notes,
      is_active,
      created_by,
      updated_by
    ) values (
      trim(p_name),
      nullif(trim(coalesce(p_contact_person, '')), ''),
      nullif(trim(coalesce(p_phone, '')), ''),
      nullif(trim(coalesce(p_email, '')), ''),
      nullif(trim(coalesce(p_city, '')), ''),
      nullif(trim(coalesce(p_street, '')), ''),
      nullif(trim(coalesce(p_nip, '')), ''),
      nullif(trim(coalesce(p_notes, '')), ''),
      coalesce(p_is_active, true),
      auth.uid(),
      auth.uid()
    )
    returning * into v_row;
  else
    update public.contractors
    set
      name = trim(p_name),
      contact_person = nullif(trim(coalesce(p_contact_person, '')), ''),
      phone = nullif(trim(coalesce(p_phone, '')), ''),
      email = nullif(trim(coalesce(p_email, '')), ''),
      city = nullif(trim(coalesce(p_city, '')), ''),
      street = nullif(trim(coalesce(p_street, '')), ''),
      nip = nullif(trim(coalesce(p_nip, '')), ''),
      notes = nullif(trim(coalesce(p_notes, '')), ''),
      is_active = coalesce(p_is_active, true),
      updated_by = auth.uid()
    where id = p_id
    returning * into v_row;

    if v_row is null then
      raise exception 'Nie znaleziono kontrahenta o id %.', p_id;
    end if;
  end if;

  return v_row;
end;
$$;

create or replace function public.admin_delete_contractor(p_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin_user() then
    raise exception 'Brak uprawnień administratora do usuwania kontrahentów.';
  end if;

  delete from public.contractors where id = p_id;
end;
$$;

grant select, insert, update, delete
  on table public.contractors
  to authenticated, service_role;

grant usage, select
  on all sequences in schema public
  to authenticated, service_role;

grant execute on function public.admin_list_contractors() to authenticated;
grant execute on function public.admin_upsert_contractor(bigint, text, text, text, text, text, text, text, text, boolean) to authenticated;
grant execute on function public.admin_delete_contractor(bigint) to authenticated;
