import {test,expect} from '@playwright/test';
test('audit A06 real FuelPanel isolates accounts and preserves distinct pending attempts in two tabs',async({page,context})=>{
 page.on('dialog',dialog=>dialog.accept());
 const mount=async(p)=>{await p.goto('/');await p.evaluate(async()=>{const m=await import('/tests/e2e/fixtures/audit-fuel.jsx');window.auditFuel=m.mountFuelHarness();});};
 const save=async(p)=>{await p.getByPlaceholder('np. 48,5').fill('40');await p.getByPlaceholder('np. 125400').fill('12000');await p.getByRole('button',{name:'Potwierdź i zapisz tankowanie'}).click();await expect(p.locator('#audit-fuel')).toContainText('CONTROLLED pending transport');};
 await mount(page);await save(page);
 const first=await page.evaluate(()=>window.auditFuel.inserts[0].id);
 const tab2=await context.newPage();await mount(tab2);
 await expect(tab2.getByPlaceholder('np. 48,5')).toHaveValue('40');
 await tab2.getByRole('button',{name:'Osobne nowe tankowanie'}).click();await save(tab2);
 const second=await tab2.evaluate(()=>window.auditFuel.inserts[0].id);expect(second).not.toBe(first);
 await mount(page);await expect(page.getByPlaceholder('np. 48,5')).toHaveValue('40');
 await page.getByRole('button',{name:'Potwierdź i zapisz tankowanie'}).click();
 await expect.poll(()=>page.evaluate(()=>window.auditFuel.inserts.length)).toBe(1);
 expect(await page.evaluate(()=>window.auditFuel.inserts[0].id)).toBe(first);
 await page.evaluate(()=>window.auditFuel.account('B'));
 await expect(page.getByPlaceholder('np. 48,5')).toHaveValue('');
 await expect(page.getByPlaceholder('np. 125400')).toHaveValue('');
 await expect(page.getByRole('button',{name:/Wznów:/})).toHaveCount(0);
 await page.evaluate(()=>window.auditFuel.account('A'));
 await expect(page.getByPlaceholder('np. 48,5')).toHaveValue('40');
 await expect(page.getByRole('button',{name:/Wznów:/})).toHaveCount(2);
 await tab2.close();
});
test('audit A11 real DevicesPanel rejects old resolve/reject across refresh, account and unmount',async({page})=>{
 await page.goto('/');
 await page.evaluate(async()=>{const m=await import('/tests/e2e/fixtures/audit-devices.jsx');window.auditDevices=m.mountDevicesHarness();});
 await page.waitForFunction(()=>window.auditDevices.pending.length>=2);
 await page.evaluate(()=>{for(let i=0;i<window.auditDevices.pending.length;i++)window.auditDevices.resolve(i,'INITIAL');});
 await expect(page.locator('#audit-devices')).toContainText('INITIAL');
 const start=await page.evaluate(()=>window.auditDevices.pending.length);
 await page.getByRole('button',{name:'Odśwież urządzenia'}).click();
 await page.waitForFunction(n=>window.auditDevices.pending.length===n+1,start);
 await page.evaluate(()=>window.auditDevices.render());
 await page.waitForFunction(n=>window.auditDevices.pending.length===n+2,start);
 await page.evaluate(n=>window.auditDevices.resolve(n+1,'NEW'),start);
 await expect(page.locator('#audit-devices')).toContainText('NEW');
 await page.evaluate(n=>window.auditDevices.resolve(n,'OLD'),start);
 await expect(page.locator('#audit-devices')).not.toContainText('OLD');
 const next=await page.evaluate(()=>window.auditDevices.pending.length);
 await page.getByRole('button',{name:'Odśwież urządzenia'}).click();
 await page.waitForFunction(n=>window.auditDevices.pending.length===n+1,next);
 await page.evaluate(()=>window.auditDevices.account('B'));
 await page.waitForFunction(n=>window.auditDevices.pending.length>=n+3,next);
 await page.evaluate(n=>{for(let i=n+1;i<window.auditDevices.pending.length;i++)window.auditDevices.resolve(i,'ACCOUNT B');window.auditDevices.reject(n);},next);
 await expect(page.locator('#audit-devices')).toContainText('ACCOUNT B');
 await expect(page.locator('#audit-devices')).not.toContainText('STALE ERROR');
 const last=await page.evaluate(()=>window.auditDevices.pending.length);
 await page.getByRole('button',{name:'Odśwież urządzenia'}).click();
 await page.waitForFunction(n=>window.auditDevices.pending.length===n+1,last);
 await page.evaluate(n=>{window.auditDevices.logout();window.auditDevices.unmount();window.auditDevices.resolve(n,'AFTER LOGOUT');},last);
 await expect(page.locator('#audit-devices')).toBeEmpty();
});
