import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const path=new URL('../../src/components/fuel/FuelPanelBase.jsx',import.meta.url);
const source=fs.readFileSync(path,'utf8');
const storage=new Map();
const context={localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)}};
vm.createContext(context);
const helpers=source.slice(source.indexOf('const FUEL_ENTRY_ATTEMPT_STORAGE_KEY'),source.indexOf('function compactFuelHistoryDate'));
vm.runInContext(helpers+';globalThis.load=loadFuelEntryAttempt;globalThis.persist=persistFuelEntryAttempt;',context);
const a={ownerUserId:'A',entryId:'operation-A',fingerprint:'fp',liters:'40',odometerKm:'12000',photoPath:'A/photo.jpg'};
context.persist(a,'A');
assert.equal(context.load('B'),null,'B must not restore any draft/entry/photo/values of A');
assert.equal(context.load('A').entryId,'operation-A');
context.persist(null,'B','operation-A');
assert.equal(context.load('A').entryId,'operation-A','B cleanup cannot clear A');
context.persist({...a,entryId:'operation-A-new'},'A');
context.persist(null,'A','operation-A');
assert.equal(context.load('A').entryId,'operation-A-new','late cleanup cannot clear newer operation');
console.log('A06 owner and conditional cleanup PASS');
