import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {stripTypeScriptTypes} from 'node:module';
import {normalizeSmsApiStatus,planSmsCallbackUpdates} from '../../supabase/functions/smsapi-delivery-webhook/security.mjs';
let source=fs.readFileSync(new URL('../../supabase/functions/smsapi-delivery-webhook/index.ts',import.meta.url),'utf8');
source=source.slice(source.indexOf('async function applyDeliveryStatus('),source.indexOf('function firstValue('));
source=stripTypeScriptTypes(source.replace('ReturnType<typeof createClient>','any'));
const ctx={normalizeSmsApiStatus,planSmsCallbackUpdates,Date,JSON};vm.createContext(ctx);vm.runInContext(source+';globalThis.apply=applyDeliveryStatus;',ctx);
const db=new PGlite();
await db.exec(`create schema private;create role anon;create role authenticated;create role service_role;
create table jobs(id uuid primary key,last_sms_status text,last_sms_error text);
create table sms_log(id uuid primary key,job_id uuid,status text,sent_at timestamptz,created_at timestamptz default now(),provider_message_id text,delivered_at timestamptz,error_message text);
create table job_protocol_email_log(sent_by uuid,protocol_id uuid,recipient_email text,status text);
insert into jobs values('00000000-0000-4000-8000-000000000001','queued',null);
insert into sms_log(id,job_id,status,provider_message_id) values('00000000-0000-4000-8000-000000000002','00000000-0000-4000-8000-000000000001','queued','id');`);
await db.exec(fs.readFileSync(new URL('../../supabase/migrations/20260917103411_audit_delivery_atomic.sql',import.meta.url),'utf8'));
let rpcUsed=false;
let row={id:'sms',job_id:null,status:'queued',sent_at:null};let release,waiting;
const blocked=new Promise(r=>release=r),reached=new Promise(r=>waiting=r);
function client(delayed){return {async rpc(name,args){rpcUsed=true;if(delayed){waiting();await blocked;} const r=await db.query('select public.apply_sms_delivery_atomic($1,$2,$3) as result',[args.p_provider_message_id,args.p_status,args.p_error]);return {data:r.rows[0].result,error:null};},from(){let patch;return {select(){return this},eq(){return this},order(){return this},limit(){return this},async maybeSingle(){return {data:{...row},error:null}},update(p){patch=p;return this},async then(resolve){if(delayed){waiting();await blocked;}Object.assign(row,patch);resolve({error:null});}}}};}
const slow=ctx.apply(client(true),{providerMessageId:'id',status:'SENT',raw:{}});await reached;
await ctx.apply(client(false),{providerMessageId:'id',status:'DELIVERED',raw:{}});assert.equal(rpcUsed?(await db.query('select status from sms_log')).rows[0].status:row.status,'delivered');
release();await slow;assert.equal(rpcUsed?(await db.query('select status from sms_log')).rows[0].status:row.status,'delivered','delayed SENT cannot regress DELIVERED');
console.log('A05 concurrent handler PASS');

assert.equal((await db.query('select last_sms_status from jobs')).rows[0].last_sms_status,'delivered');
await db.exec(`insert into sms_log(id,job_id,status,provider_message_id,created_at) values('00000000-0000-4000-8000-000000000003','00000000-0000-4000-8000-000000000001','queued','new',now()+interval '1 second');update jobs set last_sms_status='queued';`);
await ctx.apply(client(false),{providerMessageId:'id',status:'DELIVERED',raw:{}});
assert.equal((await db.query('select last_sms_status from jobs')).rows[0].last_sms_status,'queued','old delivery cannot touch new send');
await ctx.apply(client(false),{providerMessageId:'new',status:'SENT',raw:{}});
await ctx.apply(client(false),{providerMessageId:'new',status:'DELIVERED',raw:{}});
assert.equal((await db.query('select last_sms_status from jobs')).rows[0].last_sms_status,'delivered');
console.log('A05 actual RPC SQL: both orders and new send identity PASS');await db.close();
