import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {stripTypeScriptTypes} from 'node:module';import {randomUUID} from 'node:crypto';import {createClient} from '@supabase/supabase-js';
import {admin,client,database,credentials,url,evidence} from './staging-common.mjs';
import {getOrCreateProtocolEmailAttempt} from '../../src/mobile791/modules/job-protocol-email.js';
const actors=JSON.parse(fs.readFileSync(process.env.WAWIS_STAGING_ACTORS));const a=client(actors.admin.token);const db=await database();const checks=[];const deliveries=new Map();let clock=Date.now();
const ok=r=>{assert.equal(r.error,null,r.error?.message);return r.data;};
async function fixture(){const job=ok(await admin.from('jobs').insert({client:'Staging audit email '+randomUUID(),status:'Zakończone',email:'audit@example.invalid',created_by:actors.admin.id}).select().single());const path=`${job.id}/${randomUUID()}.pdf`;const bytes=new TextEncoder().encode('%PDF-1.4\n%%EOF');ok(await a.storage.from('job-protocols').upload(path,bytes,{contentType:'application/pdf'}));const record=ok(await a.from('job_protocols').insert({job_id:job.id,storage_path:path,file_name:'audit.pdf',file_size_bytes:bytes.length,signed_at:new Date().toISOString(),created_by:actors.admin.id}).select().single());return {job,record,userId:actors.admin.id,recipientEmail:job.email};}
class Clock extends Date{constructor(...args){super(...(args.length?args:[clock]));}static now(){return clock;}}
let handler;
const context={createClient,Deno:{env:{get:k=>k==='RESEND_API_KEY'?'TEST-TRANSPORT-ONLY':credentials[k]},serve:f=>handler=f},Request,Response,Blob,Uint8Array,AbortController,setTimeout,clearTimeout,btoa,Date:Clock,console,fetch:async(endpoint,options)=>{assert.equal(endpoint,'https://api.resend.com/emails');const key=options.headers['Idempotency-Key'];deliveries.set(key,(deliveries.get(key)||0)+1);throw new Error('controlled lost response after accepted; NO external email request');}};
vm.createContext(context);const source=fs.readFileSync(new URL('../../supabase/functions/send-job-protocol-email/index.ts',import.meta.url),'utf8').replace(/^import[^\n]+\n/,'');vm.runInContext(stripTypeScriptTypes(source),context);
function request(f,key){return new Request('https://staging-test.invalid',{method:'POST',headers:{Authorization:`Bearer ${actors.admin.token}`,'Content-Type':'application/json'},body:JSON.stringify({jobId:f.job.id,protocolId:f.record.id,recipientEmail:f.job.email,protocolStoragePath:f.record.storage_path,requestKey:key})});}
try{
 const storage=new Map();globalThis.localStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)};
 const A=await fixture(),B=await fixture(),C=await fixture();
 const attemptA=getOrCreateProtocolEmailAttempt(A),attemptB=getOrCreateProtocolEmailAttempt(B);assert.equal(getOrCreateProtocolEmailAttempt(A).requestKey,attemptA.requestKey);
 assert.equal((await handler(request(A,attemptA.requestKey))).status,504);assert.equal((await handler(request(B,attemptB.requestKey))).status,504);
 const reloaded=await import('../../src/mobile791/modules/job-protocol-email.js?staging-reload');assert.equal(reloaded.getOrCreateProtocolEmailAttempt(A).requestKey,attemptA.requestKey);
 clock+=25*60*60*1000;await db.query("update job_protocol_email_log set created_at=now()-interval '25 hours' where request_key=$1",[attemptA.requestKey]);assert.equal((await handler(request(A,attemptA.requestKey))).status,409);assert.equal(deliveries.size,2);assert.ok([...deliveries.values()].every(n=>n===1));checks.push('A/B/A, module reload, lost accepted response, durable DB pending aged 25h: one provider invocation per logical operation');
 const concurrent=await Promise.all([handler(request(C,randomUUID())),handler(request(C,randomUUID()))]);assert.ok(concurrent.some(r=>r.status===504));assert.equal(deliveries.size,3);assert.equal((await db.query('select count(*)::int n from job_protocol_email_log where protocol_id=$1',[C.record.id])).rows[0].n,1);checks.push('Concurrent full Edge handler requests through real Auth/PostgREST/Storage: one log and provider invocation');
 const newPath=`${A.job.id}/replacement.pdf`;ok(await a.storage.from('job-protocols').upload(newPath,new TextEncoder().encode('%PDF-1.4 replacement'),{contentType:'application/pdf'}));ok(await admin.from('job_protocols').update({storage_path:newPath,signed_at:new Date().toISOString()}).eq('id',A.record.id));assert.equal((await handler(request(A,attemptA.requestKey))).status,409);assert.equal(deliveries.size,3);checks.push('Actual Storage replacement and changed protocol version conflict with old attempt');
 const s=await database(),t=await database();let lock;
 try{
  const insert='insert into job_protocol_email_log(request_key,job_id,protocol_id,recipient_email,sent_by,protocol_storage_path) values($1,$2,$3,$4,$5,$6)';const args=[C.job.id,C.record.id,'race@example.invalid',actors.admin.id,C.record.storage_path];
  await s.query('begin');await s.query(insert,[randomUUID(),...args]);const pid=(await t.query('select pg_backend_pid() pid')).rows[0].pid;const blocked=t.query(insert,[randomUUID(),...args]).then(()=>null,e=>e.code);
  for(let i=0;i<100;i++){lock=(await db.query('select wait_event_type,pg_blocking_pids(pid) blockers from pg_stat_activity where pid=$1',[pid])).rows[0];if(lock?.wait_event_type==='Lock'&&lock.blockers.length)break;await new Promise(r=>setTimeout(r,30));}
  assert.equal(lock.wait_event_type,'Lock');await s.query('commit');assert.equal(await blocked,'23505');checks.push('Independent SQL INSERT sessions: observed unique-index contention, loser 23505, one durable version');
 }finally{await s.query('rollback');await Promise.all([s.end(),t.end()]);}
 evidence('staging-email',{checks,providerInvocations:[...deliveries.values()],transport:'controlled provider only; all Supabase Auth/REST/Storage and PostgreSQL real'});console.log('STAGING EMAIL PASS',checks);
}catch(e){evidence('staging-email-failure',{checks,error:e.message});throw e;}finally{await db.end();}
