-- WAWIS 10.89 / N7 stage B / rebuild-only indexes baseline.

drop index if exists public.app_diagnostic_events_module_received_idx;
drop index if exists public.app_diagnostic_events_received_idx;
drop index if exists public.app_diagnostic_events_user_received_idx;
drop index if exists public.contractors_company_name_unique_idx;
drop index if exists public.contractors_email_lookup_idx;
drop index if exists public.contractors_name_idx;
drop index if exists public.contractors_nip_idx;
drop index if exists public.contractors_nip_lookup_idx;
drop index if exists public.contractors_phone_lookup_idx;
drop index if exists public.contractors_tax_id_idx;
drop index if exists public.devices_contractor_id_idx;
drop index if exists public.devices_installation_date_idx;
drop index if exists public.devices_serial_number_key;
drop index if exists public.devices_service_reminder_years_idx;
drop index if exists public.devices_source_job_id_key;
drop index if exists public.devices_status_idx;
drop index if exists public.fuel_entries_created_by_idx;
drop index if exists public.fuel_entries_fueled_at_idx;
drop index if exists public.fuel_entries_vehicle_fueled_at_idx;
drop index if exists public.fuel_vehicles_created_by_idx;
drop index if exists public.idx_comments_job_id;
drop index if exists public.idx_devices_contractor_id;
drop index if exists public.idx_devices_installation_date;
drop index if exists public.idx_devices_source_job_id;
drop index if exists public.idx_job_access_job_id;
drop index if exists public.idx_job_access_user_id;
drop index if exists public.idx_jobs_contractor_id;
drop index if exists public.idx_jobs_installation_date;
drop index if exists public.idx_jobs_main_technician_id;
drop index if exists public.idx_jobs_status;
drop index if exists public.idx_photos_job_id;
drop index if exists public.idx_sms_log_device_cycle;
drop index if exists public.idx_sms_log_device_id;
drop index if exists public.idx_sms_log_device_id_created_at;
drop index if exists public.idx_sms_log_job_cycle_due;
drop index if exists public.idx_sms_log_job_id;
drop index if exists public.idx_sms_log_job_id_type;
drop index if exists public.idx_sms_log_status;
drop index if exists public.idx_sms_log_status_created_at;
drop index if exists public.idx_sms_log_status_due;
drop index if exists public.job_protocol_email_log_job_created_idx;
drop index if exists public.job_protocol_email_log_protocol_created_idx;
drop index if exists public.job_protocol_email_log_sender_created_idx;
drop index if exists public.jobs_contractor_address_id_idx;
drop index if exists public.jobs_contractor_id_idx;
drop index if exists public.jobs_device_serial_number_idx;
drop index if exists public.jobs_service_reminder_years_idx;
drop index if exists public.mobile_change_feed_audience_seq_idx;
drop index if exists public.mobile_change_feed_global_seq_idx;
drop index if exists public.nameplate_manual_verifications_job_id_idx;
drop index if exists public.nameplate_product_catalog_manufacturer_idx;
drop index if exists public.nameplate_product_catalog_model_code_idx;
drop index if exists public.photo_audit_log_job_created_idx;
drop index if exists public.photo_audit_log_job_id_idx;
drop index if exists public.photo_audit_log_photo_created_idx;
drop index if exists public.photos_job_nameplate_assignment_idx;
drop index if exists public.photos_storage_path_unique_v882;
drop index if exists public.push_subscriptions_user_active_idx;
drop index if exists public.services_device_id_idx;
drop index if exists public.services_service_due_date_idx;
drop index if exists public.services_source_job_id_idx;
drop index if exists public.services_status_idx;
drop index if exists public.sms_log_job_reminder_for_date_idx;
drop index if exists public.sms_log_job_service_cycle_idx;
drop index if exists public.uq_sms_log_active_service_reminder_cycle;

CREATE INDEX app_diagnostic_events_module_received_idx ON public.app_diagnostic_events USING btree (diagnostic_module, received_at DESC);
CREATE INDEX app_diagnostic_events_received_idx ON public.app_diagnostic_events USING btree (received_at DESC);
CREATE INDEX app_diagnostic_events_user_received_idx ON public.app_diagnostic_events USING btree (user_id, received_at DESC);
CREATE INDEX contractors_email_lookup_idx ON public.contractors USING btree (normalize_contractors_email(email));
CREATE INDEX contractors_name_idx ON public.contractors USING btree (lower(company_name));
CREATE INDEX contractors_nip_idx ON public.contractors USING btree (nip);
CREATE INDEX contractors_nip_lookup_idx ON public.contractors USING btree (normalize_contractors_nip(nip));
CREATE INDEX contractors_phone_lookup_idx ON public.contractors USING btree (normalize_contractors_phone(phone));
CREATE INDEX contractors_tax_id_idx ON public.contractors USING btree (tax_id);
CREATE INDEX devices_contractor_id_idx ON public.devices USING btree (contractor_id);
CREATE INDEX devices_installation_date_idx ON public.devices USING btree (installation_date);
CREATE INDEX devices_service_reminder_years_idx ON public.devices USING btree (service_reminder_years);
CREATE INDEX devices_status_idx ON public.devices USING btree (status);
CREATE INDEX fuel_entries_created_by_idx ON public.fuel_entries USING btree (created_by);
CREATE INDEX fuel_entries_fueled_at_idx ON public.fuel_entries USING btree (fueled_at DESC);
CREATE INDEX fuel_entries_vehicle_fueled_at_idx ON public.fuel_entries USING btree (vehicle_id, fueled_at DESC);
CREATE INDEX fuel_vehicles_created_by_idx ON public.fuel_vehicles USING btree (created_by);
CREATE INDEX idx_comments_job_id ON public.comments USING btree (job_id);
CREATE INDEX idx_devices_contractor_id ON public.devices USING btree (contractor_id);
CREATE INDEX idx_devices_installation_date ON public.devices USING btree (installation_date);
CREATE INDEX idx_devices_source_job_id ON public.devices USING btree (source_job_id);
CREATE INDEX idx_job_access_job_id ON public.job_access USING btree (job_id);
CREATE INDEX idx_job_access_user_id ON public.job_access USING btree (user_id);
CREATE INDEX idx_jobs_contractor_id ON public.jobs USING btree (contractor_id);
CREATE INDEX idx_jobs_installation_date ON public.jobs USING btree (installation_date);
CREATE INDEX idx_jobs_main_technician_id ON public.jobs USING btree (main_technician_id);
CREATE INDEX idx_jobs_status ON public.jobs USING btree (status);
CREATE INDEX idx_photos_job_id ON public.photos USING btree (job_id);
CREATE INDEX idx_sms_log_device_cycle ON public.sms_log USING btree (device_id, reminder_cycle);
CREATE INDEX idx_sms_log_device_id ON public.sms_log USING btree (device_id);
CREATE INDEX idx_sms_log_device_id_created_at ON public.sms_log USING btree (device_id, created_at DESC);
CREATE INDEX idx_sms_log_job_cycle_due ON public.sms_log USING btree (job_id, reminder_cycle, reminder_due_date, created_at DESC);
CREATE INDEX idx_sms_log_job_id ON public.sms_log USING btree (job_id);
CREATE INDEX idx_sms_log_job_id_type ON public.sms_log USING btree (job_id, sms_type);
CREATE INDEX idx_sms_log_status ON public.sms_log USING btree (status);
CREATE INDEX idx_sms_log_status_created_at ON public.sms_log USING btree (status, created_at DESC);
CREATE INDEX idx_sms_log_status_due ON public.sms_log USING btree (status, reminder_due_date, created_at DESC);
CREATE INDEX job_protocol_email_log_job_created_idx ON public.job_protocol_email_log USING btree (job_id, created_at DESC);
CREATE INDEX job_protocol_email_log_protocol_created_idx ON public.job_protocol_email_log USING btree (protocol_id, created_at DESC);
CREATE INDEX job_protocol_email_log_sender_created_idx ON public.job_protocol_email_log USING btree (sent_by, created_at DESC);
CREATE INDEX jobs_contractor_address_id_idx ON public.jobs USING btree (contractor_address_id) WHERE (contractor_address_id IS NOT NULL);
CREATE INDEX jobs_contractor_id_idx ON public.jobs USING btree (contractor_id);
CREATE INDEX jobs_device_serial_number_idx ON public.jobs USING btree (device_serial_number);
CREATE INDEX jobs_service_reminder_years_idx ON public.jobs USING btree (service_reminder_years);
CREATE INDEX mobile_change_feed_audience_seq_idx ON public.mobile_change_feed USING btree (audience_user_id, change_seq);
CREATE INDEX mobile_change_feed_global_seq_idx ON public.mobile_change_feed USING btree (change_seq) WHERE (audience_user_id IS NULL);
CREATE INDEX nameplate_manual_verifications_job_id_idx ON public.nameplate_manual_verifications USING btree (job_id);
CREATE INDEX nameplate_product_catalog_manufacturer_idx ON public.nameplate_product_catalog USING btree (lower(manufacturer));
CREATE INDEX nameplate_product_catalog_model_code_idx ON public.nameplate_product_catalog USING btree (upper(model_code)) WHERE (model_code IS NOT NULL);
CREATE INDEX photo_audit_log_job_created_idx ON public.photo_audit_log USING btree (job_id, created_at DESC);
CREATE INDEX photo_audit_log_job_id_idx ON public.photo_audit_log USING btree (job_id);
CREATE INDEX photo_audit_log_photo_created_idx ON public.photo_audit_log USING btree (photo_id, created_at DESC);
CREATE INDEX photos_job_nameplate_assignment_idx ON public.photos USING btree (job_id, photo_kind, device_index, unit_ref);
CREATE INDEX push_subscriptions_user_active_idx ON public.push_subscriptions USING btree (user_id, is_active);
CREATE INDEX services_device_id_idx ON public.services USING btree (device_id);
CREATE INDEX services_service_due_date_idx ON public.services USING btree (service_due_date);
CREATE INDEX services_source_job_id_idx ON public.services USING btree (source_job_id);
CREATE INDEX services_status_idx ON public.services USING btree (status);
CREATE INDEX sms_log_job_reminder_for_date_idx ON public.sms_log USING btree (job_id, reminder_for_date DESC);
CREATE INDEX sms_log_job_service_cycle_idx ON public.sms_log USING btree (job_id, service_cycle_number DESC);
CREATE UNIQUE INDEX contractors_company_name_unique_idx ON public.contractors USING btree (normalize_contractors_text(company_name));
CREATE UNIQUE INDEX devices_serial_number_key ON public.devices USING btree (lower(btrim(serial_number))) WHERE (NULLIF(btrim(serial_number), ''::text) IS NOT NULL);
CREATE UNIQUE INDEX devices_source_job_id_key ON public.devices USING btree (source_job_id);
CREATE UNIQUE INDEX photos_storage_path_unique_v882 ON public.photos USING btree (storage_path) WHERE ((storage_path IS NOT NULL) AND (btrim(storage_path) <> ''::text));
CREATE UNIQUE INDEX uq_sms_log_active_service_reminder_cycle ON public.sms_log USING btree (job_id, sms_type, reminder_for_date) WHERE ((sms_type = 'service_reminder'::text) AND (reminder_for_date IS NOT NULL) AND (status = ANY (ARRAY['pending_approval'::text, 'approved'::text, 'provider_sent'::text, 'sent'::text, 'delivered'::text])));
