-- WAWIS 10.89 / N7 stage B / rebuild-only triggers baseline.

drop trigger if exists archive_job_before_delete on public.jobs;
drop trigger if exists contractors_contact_duplicates_guard on public.contractors;
drop trigger if exists contractors_no_duplicates_guard on public.contractors;
drop trigger if exists contractors_set_updated_at on public.contractors;
drop trigger if exists devices_set_updated_at on public.devices;
drop trigger if exists fuel_entries_audit_correction_v1026 on public.fuel_entries;
drop trigger if exists fuel_entries_refresh_odometer_v1019 on public.fuel_entries;
drop trigger if exists fuel_entries_validate_capacity_v1025 on public.fuel_entries;
drop trigger if exists fuel_entries_validate_edit_odometer_v1026 on public.fuel_entries;
drop trigger if exists fuel_entries_validate_odometer_v1019 on public.fuel_entries;
drop trigger if exists job_access_record_mobile_change on public.job_access;
drop trigger if exists jobs_existing_contractor_guard on public.jobs;
drop trigger if exists jobs_record_mobile_change on public.jobs;
drop trigger if exists jobs_sync_device_after_change on public.jobs;
drop trigger if exists photo_audit_photos_change on public.photos;
drop trigger if exists protect_job_fields on public.jobs;
drop trigger if exists protect_profile_role on public.profiles;
drop trigger if exists services_touch_updated_at on public.services;
drop trigger if exists trg_guard_job_sms_runtime_columns on public.jobs;
drop trigger if exists trg_jobs_completion_metadata on public.jobs;
drop trigger if exists trg_jobs_nameplate_completion_guard on public.jobs;
drop trigger if exists trg_photos_completed_nameplate_guard on public.photos;
drop trigger if exists trg_photos_nameplate_job_lock on public.photos;
drop trigger if exists trg_push_subscriptions_updated_at on public.push_subscriptions;
drop trigger if exists trg_set_job_service_due_date on public.jobs;

CREATE TRIGGER archive_job_before_delete BEFORE DELETE ON public.jobs FOR EACH ROW EXECUTE FUNCTION private.archive_job_before_delete();
CREATE TRIGGER contractors_contact_duplicates_guard BEFORE INSERT OR UPDATE OF company_name, email, phone, nip ON public.contractors FOR EACH ROW EXECUTE FUNCTION public.enforce_contractors_contact_duplicates();
CREATE TRIGGER contractors_no_duplicates_guard BEFORE INSERT OR UPDATE OF company_name ON public.contractors FOR EACH ROW EXECUTE FUNCTION public.enforce_contractors_no_duplicates();
CREATE TRIGGER contractors_set_updated_at BEFORE UPDATE ON public.contractors FOR EACH ROW EXECUTE FUNCTION public.touch_contractors_updated_at();
CREATE TRIGGER devices_set_updated_at BEFORE UPDATE ON public.devices FOR EACH ROW EXECUTE FUNCTION public.touch_devices_updated_at();
CREATE TRIGGER fuel_entries_audit_correction_v1026 BEFORE UPDATE ON public.fuel_entries FOR EACH ROW EXECUTE FUNCTION private.audit_fuel_entry_correction_v1026();
CREATE TRIGGER fuel_entries_refresh_odometer_v1019 AFTER INSERT OR DELETE OR UPDATE ON public.fuel_entries FOR EACH ROW EXECUTE FUNCTION private.refresh_fuel_vehicle_odometer_v1019();
CREATE TRIGGER fuel_entries_validate_capacity_v1025 BEFORE INSERT OR UPDATE OF vehicle_id, liters ON public.fuel_entries FOR EACH ROW EXECUTE FUNCTION private.validate_fuel_entry_capacity_v1025();
CREATE TRIGGER fuel_entries_validate_edit_odometer_v1026 BEFORE UPDATE OF odometer_km ON public.fuel_entries FOR EACH ROW EXECUTE FUNCTION private.validate_fuel_entry_edit_odometer_v1026();
CREATE TRIGGER fuel_entries_validate_odometer_v1019 BEFORE INSERT ON public.fuel_entries FOR EACH ROW EXECUTE FUNCTION private.validate_fuel_entry_odometer_v1019();
CREATE TRIGGER job_access_record_mobile_change AFTER INSERT OR DELETE OR UPDATE ON public.job_access FOR EACH ROW EXECUTE FUNCTION public.record_mobile_job_access_change();
CREATE TRIGGER jobs_existing_contractor_guard BEFORE INSERT OR UPDATE OF client, contractor_id ON public.jobs FOR EACH ROW EXECUTE FUNCTION public.enforce_jobs_use_existing_contractor();
CREATE TRIGGER jobs_record_mobile_change AFTER INSERT OR DELETE OR UPDATE ON public.jobs FOR EACH ROW EXECUTE FUNCTION public.record_mobile_job_change();
CREATE TRIGGER jobs_sync_device_after_change AFTER INSERT OR DELETE OR UPDATE OF contractor_id, device_model, device_serial_number, installation_date ON public.jobs FOR EACH ROW EXECUTE FUNCTION public.sync_device_from_job_trigger();
CREATE TRIGGER photo_audit_photos_change AFTER INSERT OR DELETE OR UPDATE ON public.photos FOR EACH ROW EXECUTE FUNCTION public.photo_audit_photos_change_trigger();
CREATE TRIGGER protect_job_fields BEFORE INSERT OR UPDATE ON public.jobs FOR EACH ROW EXECUTE FUNCTION private.guard_job_fields();
CREATE TRIGGER protect_profile_role BEFORE INSERT OR UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION private.guard_profile_role();
CREATE TRIGGER services_touch_updated_at BEFORE UPDATE ON public.services FOR EACH ROW EXECUTE FUNCTION public.touch_services_updated_at();
CREATE TRIGGER trg_guard_job_sms_runtime_columns BEFORE UPDATE OF last_sms_sent_at, last_sms_status, last_sms_error ON public.jobs FOR EACH ROW EXECUTE FUNCTION public.guard_job_sms_runtime_columns();
CREATE TRIGGER trg_jobs_completion_metadata BEFORE INSERT OR UPDATE OF status ON public.jobs FOR EACH ROW EXECUTE FUNCTION public.set_job_completion_metadata();
CREATE TRIGGER trg_jobs_nameplate_completion_guard BEFORE INSERT OR UPDATE ON public.jobs FOR EACH ROW EXECUTE FUNCTION private.guard_job_completion_nameplates();
CREATE TRIGGER trg_photos_completed_nameplate_guard AFTER DELETE OR UPDATE ON public.photos FOR EACH ROW EXECUTE FUNCTION private.guard_completed_job_nameplates_after_photo_mutation();
CREATE TRIGGER trg_photos_nameplate_job_lock BEFORE INSERT OR DELETE OR UPDATE ON public.photos FOR EACH ROW EXECUTE FUNCTION private.lock_job_for_photo_mutation();
CREATE TRIGGER trg_push_subscriptions_updated_at BEFORE UPDATE ON public.push_subscriptions FOR EACH ROW EXECUTE FUNCTION public.touch_push_subscriptions_updated_at();
CREATE TRIGGER trg_set_job_service_due_date BEFORE INSERT OR UPDATE OF installation_date, phone, sms_recipient_phone ON public.jobs FOR EACH ROW EXECUTE FUNCTION public.set_job_service_due_date();

drop event trigger if exists ensure_rls;
create event trigger ensure_rls on ddl_command_end when tag in ('CREATE TABLE','CREATE TABLE AS','SELECT INTO') execute function public.rls_auto_enable();
