-- WAWIS 10.89 / N7 stage B / rebuild-only RLS baseline.
-- Includes the intentional 10.89 contractor read correction: approved staff may SELECT contractors; writes remain admin-only.

do $$ declare r record; begin
  for r in select tablename,policyname from pg_policies where schemaname='public' loop
    execute format('drop policy if exists %I on public.%I',r.policyname,r.tablename);
  end loop;
  for r in select c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in ('r','p') loop
    execute format('alter table public.%I enable row level security',r.relname);
  end loop;
end $$;

create policy "services admin delete" on public.services as permissive for delete to authenticated using (current_user_is_admin());
create policy "services admin insert" on public.services as permissive for insert to authenticated with check (current_user_is_admin());
create policy "services admin read" on public.services as permissive for select to authenticated using (current_user_is_admin());
create policy "services admin update" on public.services as permissive for update to authenticated using (current_user_is_admin()) with check (current_user_is_admin());
create policy access_delete_staff on public.job_access as permissive for delete to authenticated using (current_user_can_edit_job(job_id));
create policy access_insert_staff on public.job_access as permissive for insert to authenticated with check ((current_user_can_edit_job(job_id) AND (EXISTS ( SELECT 1 FROM profiles target WHERE ((target.id = job_access.user_id) AND (lower(TRIM(BOTH FROM COALESCE(target.role, ''::text))) = ANY (ARRAY['employee'::text, 'pracownik'::text, 'admin'::text, 'administrator'::text])))))));
create policy access_read_job on public.job_access as permissive for select to authenticated using (current_user_can_view_job(job_id));
create policy app_diagnostic_events_admin_delete on public.app_diagnostic_events as permissive for delete to authenticated using (( SELECT current_user_is_admin() AS current_user_is_admin));
create policy app_diagnostic_events_admin_read on public.app_diagnostic_events as permissive for select to authenticated using (( SELECT current_user_is_admin() AS current_user_is_admin));
create policy app_diagnostic_events_insert_own on public.app_diagnostic_events as permissive for insert to authenticated with check ((( SELECT auth.uid() AS uid) = user_id));
create policy comments_delete_admin on public.comments as permissive for delete to authenticated using (current_user_is_admin());
create policy comments_insert_job on public.comments as permissive for insert to authenticated with check (((author_id = auth.uid()) AND current_user_can_view_job(job_id) AND (EXISTS ( SELECT 1 FROM jobs j WHERE ((j.id = comments.job_id) AND (current_user_is_admin() OR (j.status IS DISTINCT FROM 'Zakończone'::text)))))));
create policy comments_read_job on public.comments as permissive for select to authenticated using (current_user_can_view_job(job_id));
create policy contractors_admin_delete on public.contractors as permissive for delete to authenticated using (current_user_is_admin());
create policy contractors_admin_insert on public.contractors as permissive for insert to authenticated with check (current_user_is_admin());
create policy contractors_staff_select on public.contractors as permissive for select to authenticated using (current_user_is_staff());
create policy contractors_admin_update on public.contractors as permissive for update to authenticated using (current_user_is_admin()) with check (current_user_is_admin());
create policy devices_admin_delete on public.devices as permissive for delete to public using (current_user_is_admin());
create policy devices_admin_insert on public.devices as permissive for insert to public with check (current_user_is_admin());
create policy devices_admin_select on public.devices as permissive for select to public using (current_user_is_admin());
create policy devices_admin_update on public.devices as permissive for update to public using (current_user_is_admin()) with check (current_user_is_admin());
create policy fuel_entries_admin_delete on public.fuel_entries as permissive for delete to authenticated using (( SELECT current_user_is_admin() AS current_user_is_admin));
create policy fuel_entries_admin_update on public.fuel_entries as permissive for update to authenticated using (( SELECT current_user_is_admin() AS current_user_is_admin)) with check (( SELECT current_user_is_admin() AS current_user_is_admin));
create policy fuel_entries_own_insert on public.fuel_entries as permissive for insert to authenticated with check ((( SELECT current_user_is_staff() AS current_user_is_staff) AND (created_by = ( SELECT auth.uid() AS uid))));
create policy fuel_entries_own_or_admin_select on public.fuel_entries as permissive for select to authenticated using ((( SELECT current_user_is_staff() AS current_user_is_staff) AND ((created_by = ( SELECT auth.uid() AS uid)) OR ( SELECT current_user_is_admin() AS current_user_is_admin))));
create policy fuel_vehicles_admin_delete on public.fuel_vehicles as permissive for delete to authenticated using (( SELECT current_user_is_admin() AS current_user_is_admin));
create policy fuel_vehicles_admin_insert on public.fuel_vehicles as permissive for insert to authenticated with check ((( SELECT current_user_is_admin() AS current_user_is_admin) AND (created_by = ( SELECT auth.uid() AS uid))));
create policy fuel_vehicles_admin_update on public.fuel_vehicles as permissive for update to authenticated using (( SELECT current_user_is_admin() AS current_user_is_admin)) with check (( SELECT current_user_is_admin() AS current_user_is_admin));
create policy fuel_vehicles_fleet_select on public.fuel_vehicles as permissive for select to authenticated using ((( SELECT current_user_is_staff() AS current_user_is_staff) AND (is_active OR ( SELECT current_user_is_admin() AS current_user_is_admin))));
create policy job_protocol_email_log_select_accessible_job on public.job_protocol_email_log as permissive for select to authenticated using (current_user_can_view_job(job_id));
create policy job_protocols_insert_completed_job on public.job_protocols as permissive for insert to authenticated with check (((created_by = auth.uid()) AND current_user_can_finalize_job(job_id)));
create policy job_protocols_select_accessible_job on public.job_protocols as permissive for select to authenticated using (current_user_can_view_job(job_id));
create policy job_protocols_update_owner_or_admin on public.job_protocols as permissive for update to authenticated using ((current_user_can_access_job(job_id) AND (current_user_is_admin() OR (created_by = auth.uid())))) with check (((created_by = auth.uid()) AND current_user_can_finalize_job(job_id)));
create policy jobs_create_own on public.jobs as permissive for insert to authenticated with check ((current_user_is_staff() AND ((created_by = auth.uid()) OR current_user_is_admin())));
create policy jobs_delete_admin on public.jobs as permissive for delete to authenticated using (current_user_is_admin());
create policy jobs_read_access on public.jobs as permissive for select to authenticated using (current_user_is_staff());
create policy jobs_update_access on public.jobs as permissive for update to authenticated using (current_user_can_edit_job(id)) with check (current_user_can_edit_job(id));
create policy mobile_change_feed_staff_global_select on public.mobile_change_feed as permissive for select to authenticated using (((audience_user_id IS NULL) AND current_user_is_staff()));
create policy nameplate_manual_verifications_admin_delete on public.nameplate_manual_verifications as permissive for delete to authenticated using (current_user_is_admin());
create policy nameplate_manual_verifications_admin_insert on public.nameplate_manual_verifications as permissive for insert to authenticated with check (current_user_is_admin());
create policy nameplate_manual_verifications_admin_select on public.nameplate_manual_verifications as permissive for select to authenticated using (( SELECT current_user_is_admin() AS current_user_is_admin));
create policy nameplate_manual_verifications_admin_update on public.nameplate_manual_verifications as permissive for update to authenticated using (current_user_is_admin()) with check (current_user_is_admin());
create policy nameplate_product_catalog_admin_delete on public.nameplate_product_catalog as permissive for delete to authenticated using (current_user_is_admin());
create policy nameplate_product_catalog_admin_insert on public.nameplate_product_catalog as permissive for insert to authenticated with check (current_user_is_admin());
create policy nameplate_product_catalog_admin_select on public.nameplate_product_catalog as permissive for select to authenticated using (current_user_is_admin());
create policy nameplate_product_catalog_admin_update on public.nameplate_product_catalog as permissive for update to authenticated using (current_user_is_admin()) with check (current_user_is_admin());
create policy notifications_insert_job on public.notifications as permissive for insert to authenticated with check ((current_user_is_admin() OR (current_user_can_access_job(link_job_id) AND ((EXISTS ( SELECT 1 FROM profiles p WHERE ((p.id = notifications.user_id) AND (lower(p.role) = ANY (ARRAY['administrator'::text, 'admin'::text]))))) OR (EXISTS ( SELECT 1 FROM job_access a WHERE ((a.job_id = notifications.link_job_id) AND (a.user_id = notifications.user_id)))) OR (EXISTS ( SELECT 1 FROM jobs j WHERE ((j.id = notifications.link_job_id) AND ((j.created_by = notifications.user_id) OR (j.main_technician_id = notifications.user_id)))))))));
create policy notifications_read_own on public.notifications as permissive for select to authenticated using ((user_id = auth.uid()));
create policy notifications_update_own on public.notifications as permissive for update to authenticated using ((user_id = auth.uid())) with check ((user_id = auth.uid()));
create policy photo_audit_log_admin_read on public.photo_audit_log as permissive for select to authenticated using (current_user_is_admin());
create policy photo_audit_log_service_insert on public.photo_audit_log as permissive for insert to authenticated with check ((auth.uid() IS NOT NULL));
create policy photos_delete_job on public.photos as permissive for delete to authenticated using ((current_user_can_access_job(job_id) AND (EXISTS ( SELECT 1 FROM jobs j WHERE ((j.id = photos.job_id) AND (current_user_is_admin() OR (j.status IS DISTINCT FROM 'Zakończone'::text)))))));
create policy photos_insert_job on public.photos as permissive for insert to authenticated with check ((current_user_can_access_job(job_id) AND ((uploaded_by = auth.uid()) OR current_user_is_admin()) AND (EXISTS ( SELECT 1 FROM jobs j WHERE ((j.id = photos.job_id) AND (current_user_is_admin() OR (j.status IS DISTINCT FROM 'Zakończone'::text)))))));
create policy photos_read_job on public.photos as permissive for select to authenticated using (current_user_can_view_job(job_id));
create policy photos_update_job on public.photos as permissive for update to authenticated using ((current_user_can_access_job(job_id) AND (EXISTS ( SELECT 1 FROM jobs j WHERE ((j.id = photos.job_id) AND (current_user_is_admin() OR (j.status IS DISTINCT FROM 'Zakończone'::text))))))) with check (current_user_can_access_job(job_id));
create policy profiles_read_team on public.profiles as permissive for select to authenticated using (((id = ( SELECT auth.uid() AS uid)) OR ( SELECT current_user_is_staff() AS current_user_is_staff)));
create policy profiles_update_self_or_admin on public.profiles as permissive for update to authenticated using (((id = auth.uid()) OR current_user_is_admin())) with check (((id = auth.uid()) OR current_user_is_admin()));
create policy push_delivery_log_select_own on public.push_delivery_log as permissive for select to public using ((auth.uid() = user_id));
create policy push_subscriptions_insert_own on public.push_subscriptions as permissive for insert to public with check ((auth.uid() = user_id));
create policy push_subscriptions_select_own on public.push_subscriptions as permissive for select to public using ((auth.uid() = user_id));
create policy push_subscriptions_update_own on public.push_subscriptions as permissive for update to public using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy sms_log_admin_delete on public.sms_log as permissive for delete to public using (current_user_is_admin());
create policy sms_log_admin_insert on public.sms_log as permissive for insert to public with check (current_user_is_admin());
create policy sms_log_admin_select on public.sms_log as permissive for select to public using (current_user_is_admin());
create policy sms_log_admin_update on public.sms_log as permissive for update to public using (current_user_is_admin()) with check (current_user_is_admin());
create policy sms_settings_admin_delete on public.sms_settings as permissive for delete to public using (current_user_is_admin());
create policy sms_settings_admin_insert on public.sms_settings as permissive for insert to public with check (current_user_is_admin());
create policy sms_settings_admin_select on public.sms_settings as permissive for select to public using (current_user_is_admin());
create policy sms_settings_admin_update on public.sms_settings as permissive for update to public using (current_user_is_admin()) with check (current_user_is_admin());
