-- WAWIS 10.89 / N7 stage B / rebuild-only constraints baseline.
-- Captured from the isolated staging rebuild after historical replay.

alter table public.app_diagnostic_events drop constraint if exists app_diagnostic_events_diagnostic_module_length_check cascade;
alter table public.app_diagnostic_events drop constraint if exists app_diagnostic_events_lengths_check cascade;
alter table public.app_diagnostic_events drop constraint if exists app_diagnostic_events_pkey cascade;
alter table public.app_diagnostic_events drop constraint if exists app_diagnostic_events_severity_check cascade;
alter table public.app_diagnostic_events drop constraint if exists app_diagnostic_events_user_id_client_event_id_key cascade;
alter table public.app_diagnostic_events drop constraint if exists app_diagnostic_events_user_id_fkey cascade;
alter table public.comments drop constraint if exists comments_job_id_fkey cascade;
alter table public.comments drop constraint if exists comments_pkey cascade;
alter table public.contractors drop constraint if exists contractors_pkey cascade;
alter table public.devices drop constraint if exists devices_contractor_id_fkey cascade;
alter table public.devices drop constraint if exists devices_pkey cascade;
alter table public.devices drop constraint if exists devices_service_reminder_years_check cascade;
alter table public.devices drop constraint if exists devices_status_check cascade;
alter table public.fuel_entries drop constraint if exists fuel_entries_ai_confidence_range cascade;
alter table public.fuel_entries drop constraint if exists fuel_entries_corrected_by_fkey cascade;
alter table public.fuel_entries drop constraint if exists fuel_entries_correction_count_nonnegative cascade;
alter table public.fuel_entries drop constraint if exists fuel_entries_created_by_fkey cascade;
alter table public.fuel_entries drop constraint if exists fuel_entries_liters_range cascade;
alter table public.fuel_entries drop constraint if exists fuel_entries_odometer_range cascade;
alter table public.fuel_entries drop constraint if exists fuel_entries_odometer_read_source_check cascade;
alter table public.fuel_entries drop constraint if exists fuel_entries_pkey cascade;
alter table public.fuel_entries drop constraint if exists fuel_entries_vehicle_id_fkey cascade;
alter table public.fuel_vehicles drop constraint if exists fuel_vehicles_created_by_fkey cascade;
alter table public.fuel_vehicles drop constraint if exists fuel_vehicles_last_odometer_range cascade;
alter table public.fuel_vehicles drop constraint if exists fuel_vehicles_pkey cascade;
alter table public.fuel_vehicles drop constraint if exists fuel_vehicles_registration_format cascade;
alter table public.fuel_vehicles drop constraint if exists fuel_vehicles_registration_number_key cascade;
alter table public.fuel_vehicles drop constraint if exists fuel_vehicles_tank_capacity_range cascade;
alter table public.job_access drop constraint if exists job_access_job_id_fkey cascade;
alter table public.job_access drop constraint if exists job_access_pkey cascade;
alter table public.job_protocol_email_log drop constraint if exists job_protocol_email_log_job_id_fkey cascade;
alter table public.job_protocol_email_log drop constraint if exists job_protocol_email_log_pkey cascade;
alter table public.job_protocol_email_log drop constraint if exists job_protocol_email_log_protocol_id_fkey cascade;
alter table public.job_protocol_email_log drop constraint if exists job_protocol_email_log_recipient_check cascade;
alter table public.job_protocol_email_log drop constraint if exists job_protocol_email_log_request_key_key cascade;
alter table public.job_protocol_email_log drop constraint if exists job_protocol_email_log_sender_check cascade;
alter table public.job_protocol_email_log drop constraint if exists job_protocol_email_log_sent_by_fkey cascade;
alter table public.job_protocol_email_log drop constraint if exists job_protocol_email_log_status_check cascade;
alter table public.job_protocols drop constraint if exists job_protocols_created_by_fkey cascade;
alter table public.job_protocols drop constraint if exists job_protocols_file_size_bytes_check cascade;
alter table public.job_protocols drop constraint if exists job_protocols_job_id_fkey cascade;
alter table public.job_protocols drop constraint if exists job_protocols_job_id_key cascade;
alter table public.job_protocols drop constraint if exists job_protocols_pkey cascade;
alter table public.job_protocols drop constraint if exists job_protocols_storage_path_key cascade;
alter table public.jobs drop constraint if exists jobs_completed_by_fkey cascade;
alter table public.jobs drop constraint if exists jobs_contractor_id_fkey cascade;
alter table public.jobs drop constraint if exists jobs_main_technician_id_fkey cascade;
alter table public.jobs drop constraint if exists jobs_payment_confirmation_consistent cascade;
alter table public.jobs drop constraint if exists jobs_payment_recorded_by_fkey cascade;
alter table public.jobs drop constraint if exists jobs_pkey cascade;
alter table public.jobs drop constraint if exists jobs_service_reminder_years_check cascade;
alter table public.mobile_change_feed drop constraint if exists mobile_change_feed_audience_user_id_fkey cascade;
alter table public.mobile_change_feed drop constraint if exists mobile_change_feed_pkey cascade;
alter table public.nameplate_manual_verifications drop constraint if exists nameplate_manual_verifications_device_index_check cascade;
alter table public.nameplate_manual_verifications drop constraint if exists nameplate_manual_verifications_job_id_fkey cascade;
alter table public.nameplate_manual_verifications drop constraint if exists nameplate_manual_verifications_job_unit_unique cascade;
alter table public.nameplate_manual_verifications drop constraint if exists nameplate_manual_verifications_pkey cascade;
alter table public.nameplate_manual_verifications drop constraint if exists nameplate_manual_verifications_unit_ref_check cascade;
alter table public.nameplate_product_catalog drop constraint if exists nameplate_product_catalog_created_by_fkey cascade;
alter table public.nameplate_product_catalog drop constraint if exists nameplate_product_catalog_ean_check cascade;
alter table public.nameplate_product_catalog drop constraint if exists nameplate_product_catalog_pkey cascade;
alter table public.nameplate_product_catalog drop constraint if exists nameplate_product_catalog_source_type_check cascade;
alter table public.nameplate_product_catalog drop constraint if exists nameplate_product_catalog_unit_type_check cascade;
alter table public.notifications drop constraint if exists notifications_pkey cascade;
alter table public.notifications drop constraint if exists notifications_user_id_fkey cascade;
alter table public.photo_audit_log drop constraint if exists photo_audit_log_pkey cascade;
alter table public.photos drop constraint if exists photos_job_id_fkey cascade;
alter table public.photos drop constraint if exists photos_ocr_status_check cascade;
alter table public.photos drop constraint if exists photos_pkey cascade;
alter table public.profiles drop constraint if exists profiles_email_key cascade;
alter table public.profiles drop constraint if exists profiles_id_fkey cascade;
alter table public.profiles drop constraint if exists profiles_pkey cascade;
alter table public.push_delivery_log drop constraint if exists push_delivery_log_job_id_fkey cascade;
alter table public.push_delivery_log drop constraint if exists push_delivery_log_pkey cascade;
alter table public.push_delivery_log drop constraint if exists push_delivery_log_user_id_fkey cascade;
alter table public.push_subscriptions drop constraint if exists push_subscriptions_endpoint_key cascade;
alter table public.push_subscriptions drop constraint if exists push_subscriptions_pkey cascade;
alter table public.push_subscriptions drop constraint if exists push_subscriptions_user_id_fkey cascade;
alter table public.services drop constraint if exists services_pkey cascade;
alter table public.services drop constraint if exists services_status_check cascade;
alter table public.sms_log drop constraint if exists sms_log_approved_by_fkey cascade;
alter table public.sms_log drop constraint if exists sms_log_created_by_fkey cascade;
alter table public.sms_log drop constraint if exists sms_log_device_id_fkey cascade;
alter table public.sms_log drop constraint if exists sms_log_job_id_fkey cascade;
alter table public.sms_log drop constraint if exists sms_log_pkey cascade;
alter table public.sms_settings drop constraint if exists sms_settings_pkey cascade;
alter table public.sms_settings drop constraint if exists sms_settings_sending_mode_check cascade;

alter table public.app_diagnostic_events add constraint app_diagnostic_events_diagnostic_module_length_check CHECK (length(diagnostic_module) <= 80);
alter table public.app_diagnostic_events add constraint app_diagnostic_events_lengths_check CHECK (length(client_event_id) >= 8 AND length(client_event_id) <= 180 AND length(event_type) <= 120 AND length(app_version) <= 24 AND length(platform) <= 24 AND length(error_code) <= 80 AND length(error_message) <= 500);
alter table public.app_diagnostic_events add constraint app_diagnostic_events_pkey PRIMARY KEY (id);
alter table public.app_diagnostic_events add constraint app_diagnostic_events_severity_check CHECK (severity = ANY (ARRAY['warning'::text, 'error'::text]));
alter table public.app_diagnostic_events add constraint app_diagnostic_events_user_id_client_event_id_key UNIQUE (user_id, client_event_id);
alter table public.comments add constraint comments_pkey PRIMARY KEY (id);
alter table public.contractors add constraint contractors_pkey PRIMARY KEY (id);
alter table public.devices add constraint devices_pkey PRIMARY KEY (id);
alter table public.devices add constraint devices_service_reminder_years_check CHECK (service_reminder_years >= 1 AND service_reminder_years <= 10);
alter table public.devices add constraint devices_status_check CHECK (status = ANY (ARRAY['aktywne'::text, 'do_serwisu'::text, 'zdemontowane'::text]));
alter table public.fuel_entries add constraint fuel_entries_ai_confidence_range CHECK (odometer_ai_confidence IS NULL OR odometer_ai_confidence >= 0::numeric AND odometer_ai_confidence <= 1::numeric);
alter table public.fuel_entries add constraint fuel_entries_correction_count_nonnegative CHECK (correction_count >= 0);
alter table public.fuel_entries add constraint fuel_entries_liters_range CHECK (liters > 0::numeric AND liters <= 500::numeric);
alter table public.fuel_entries add constraint fuel_entries_odometer_range CHECK (odometer_km >= 0 AND odometer_km <= 5000000);
alter table public.fuel_entries add constraint fuel_entries_odometer_read_source_check CHECK (odometer_read_source = ANY (ARRAY['local_ocr'::text, 'openai'::text, 'manual'::text]));
alter table public.fuel_entries add constraint fuel_entries_pkey PRIMARY KEY (id);
alter table public.fuel_vehicles add constraint fuel_vehicles_last_odometer_range CHECK (last_odometer_km IS NULL OR last_odometer_km >= 0 AND last_odometer_km <= 5000000);
alter table public.fuel_vehicles add constraint fuel_vehicles_pkey PRIMARY KEY (id);
alter table public.fuel_vehicles add constraint fuel_vehicles_registration_format CHECK (registration_number = upper(btrim(registration_number)) AND length(registration_number) >= 2 AND length(registration_number) <= 16);
alter table public.fuel_vehicles add constraint fuel_vehicles_registration_number_key UNIQUE (registration_number);
alter table public.fuel_vehicles add constraint fuel_vehicles_tank_capacity_range CHECK (tank_capacity_liters IS NULL OR tank_capacity_liters > 0::numeric AND tank_capacity_liters <= 500::numeric);
alter table public.job_access add constraint job_access_pkey PRIMARY KEY (id);
alter table public.job_protocol_email_log add constraint job_protocol_email_log_pkey PRIMARY KEY (id);
alter table public.job_protocol_email_log add constraint job_protocol_email_log_recipient_check CHECK (recipient_email = lower(recipient_email) AND length(recipient_email) >= 3 AND length(recipient_email) <= 254);
alter table public.job_protocol_email_log add constraint job_protocol_email_log_request_key_key UNIQUE (request_key);
alter table public.job_protocol_email_log add constraint job_protocol_email_log_sender_check CHECK (sender_email = 'biuro@wawis.pl'::text);
alter table public.job_protocol_email_log add constraint job_protocol_email_log_status_check CHECK (status = ANY (ARRAY['sending'::text, 'sent'::text, 'failed'::text]));
alter table public.job_protocols add constraint job_protocols_file_size_bytes_check CHECK (file_size_bytes > 0 AND file_size_bytes <= 10485760);
alter table public.job_protocols add constraint job_protocols_job_id_key UNIQUE (job_id);
alter table public.job_protocols add constraint job_protocols_pkey PRIMARY KEY (id);
alter table public.job_protocols add constraint job_protocols_storage_path_key UNIQUE (storage_path);
alter table public.jobs add constraint jobs_payment_confirmation_consistent CHECK (payment_confirmation_enabled = false AND payment_amount IS NULL AND payment_kind IS NULL AND payment_method IS NULL AND payment_paid_at IS NULL OR payment_confirmation_enabled = true AND payment_amount > 0::numeric AND (payment_kind = ANY (ARRAY['full'::text, 'deposit'::text])) AND (payment_method = ANY (ARRAY['cash'::text, 'transfer'::text, 'card'::text, 'blik'::text])) AND payment_paid_at IS NOT NULL);
alter table public.jobs add constraint jobs_pkey PRIMARY KEY (id);
alter table public.jobs add constraint jobs_service_reminder_years_check CHECK (service_reminder_years >= 1 AND service_reminder_years <= 10);
alter table public.mobile_change_feed add constraint mobile_change_feed_pkey PRIMARY KEY (change_seq);
alter table public.nameplate_manual_verifications add constraint nameplate_manual_verifications_device_index_check CHECK (device_index >= 1);
alter table public.nameplate_manual_verifications add constraint nameplate_manual_verifications_job_unit_unique UNIQUE (job_id, device_index, unit_ref);
alter table public.nameplate_manual_verifications add constraint nameplate_manual_verifications_pkey PRIMARY KEY (id);
alter table public.nameplate_manual_verifications add constraint nameplate_manual_verifications_unit_ref_check CHECK (unit_ref = 'jz'::text OR unit_ref ~ '^jw-[1-5]$'::text);
alter table public.nameplate_product_catalog add constraint nameplate_product_catalog_ean_check CHECK (ean ~ '^[0-9]{13}$'::text);
alter table public.nameplate_product_catalog add constraint nameplate_product_catalog_pkey PRIMARY KEY (ean);
alter table public.nameplate_product_catalog add constraint nameplate_product_catalog_source_type_check CHECK (source_type = ANY (ARRAY['manual'::text, 'confirmed_scan'::text, 'import'::text, 'manufacturer'::text, 'gs1'::text, 'local_dictionary'::text]));
alter table public.nameplate_product_catalog add constraint nameplate_product_catalog_unit_type_check CHECK (unit_type = ANY (ARRAY['indoor'::text, 'outdoor'::text, 'unknown'::text]));
alter table public.notifications add constraint notifications_pkey PRIMARY KEY (id);
alter table public.photo_audit_log add constraint photo_audit_log_pkey PRIMARY KEY (id);
alter table public.photos add constraint photos_ocr_status_check CHECK (ocr_status IS NULL OR (ocr_status = ANY (ARRAY['pending'::text, 'approved'::text])));
alter table public.photos add constraint photos_pkey PRIMARY KEY (id);
alter table public.profiles add constraint profiles_email_key UNIQUE (email);
alter table public.profiles add constraint profiles_pkey PRIMARY KEY (id);
alter table public.push_delivery_log add constraint push_delivery_log_pkey PRIMARY KEY (id);
alter table public.push_subscriptions add constraint push_subscriptions_endpoint_key UNIQUE (endpoint);
alter table public.push_subscriptions add constraint push_subscriptions_pkey PRIMARY KEY (id);
alter table public.services add constraint services_pkey PRIMARY KEY (id);
alter table public.services add constraint services_status_check CHECK (status = ANY (ARRAY['do_kontaktu'::text, 'umowione'::text, 'w_trakcie'::text, 'wykonane'::text, 'odmowione'::text]));
alter table public.sms_log add constraint sms_log_pkey PRIMARY KEY (id);
alter table public.sms_settings add constraint sms_settings_pkey PRIMARY KEY (id);
alter table public.sms_settings add constraint sms_settings_sending_mode_check CHECK (sending_mode = ANY (ARRAY['approval'::text, 'auto'::text]));

alter table public.app_diagnostic_events add constraint app_diagnostic_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.comments add constraint comments_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
alter table public.devices add constraint devices_contractor_id_fkey FOREIGN KEY (contractor_id) REFERENCES contractors(id) ON DELETE SET NULL;
alter table public.fuel_entries add constraint fuel_entries_corrected_by_fkey FOREIGN KEY (corrected_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.fuel_entries add constraint fuel_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public.fuel_entries add constraint fuel_entries_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES fuel_vehicles(id);
alter table public.fuel_vehicles add constraint fuel_vehicles_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public.job_access add constraint job_access_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
alter table public.job_protocol_email_log add constraint job_protocol_email_log_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
alter table public.job_protocol_email_log add constraint job_protocol_email_log_protocol_id_fkey FOREIGN KEY (protocol_id) REFERENCES job_protocols(id) ON DELETE CASCADE;
alter table public.job_protocol_email_log add constraint job_protocol_email_log_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.job_protocols add constraint job_protocols_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.job_protocols add constraint job_protocols_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
alter table public.jobs add constraint jobs_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.jobs add constraint jobs_contractor_id_fkey FOREIGN KEY (contractor_id) REFERENCES contractors(id) ON DELETE SET NULL;
alter table public.jobs add constraint jobs_main_technician_id_fkey FOREIGN KEY (main_technician_id) REFERENCES profiles(id);
alter table public.jobs add constraint jobs_payment_recorded_by_fkey FOREIGN KEY (payment_recorded_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.mobile_change_feed add constraint mobile_change_feed_audience_user_id_fkey FOREIGN KEY (audience_user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.nameplate_manual_verifications add constraint nameplate_manual_verifications_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
alter table public.nameplate_product_catalog add constraint nameplate_product_catalog_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.notifications add constraint notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.photos add constraint photos_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
alter table public.profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.push_delivery_log add constraint push_delivery_log_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE SET NULL;
alter table public.push_delivery_log add constraint push_delivery_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.push_subscriptions add constraint push_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.sms_log add constraint sms_log_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES profiles(id);
alter table public.sms_log add constraint sms_log_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public.sms_log add constraint sms_log_device_id_fkey FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE;
alter table public.sms_log add constraint sms_log_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
