const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const { resolveSqlPath } = require('./sql-paths.cjs');

const root = path.resolve(__dirname, '..');
const appVersionPath = path.join(root, 'app-version.json');
const packagePath = path.join(root, 'package.json');
const packageLockPath = path.join(root, 'package-lock.json');
const npmrcPath = path.join(root, '.npmrc');
const readmePath = path.join(root, 'README.md');
const changelogPath = path.join(root, 'CHANGELOG.md');
const releaseChecklistPath = path.join(root, 'RELEASE-CHECKLIST.md');
const runReleasePath = path.join(root, 'scripts', 'run-release.cjs');
const smokeReleaseRunnerPath = path.join(root, 'scripts', 'smoke-release-runner.cjs');
const ensureBuildDepsPath = path.join(root, 'scripts', 'ensure-build-deps.cjs');
const smokeWindowsNpmRunnerPath = path.join(root, 'scripts', 'smoke-windows-npm-runner.cjs');
const smokeNpmRegistryPath = path.join(root, 'scripts', 'smoke-npm-registry.cjs');
const smokeReleaseZipPath = path.join(root, 'scripts', 'smoke-release-zip.cjs');
const smokeReleaseZipCleanPath = path.join(root, 'scripts', 'smoke-release-zip-clean.cjs');
const smokeCalendarWidthPath = path.join(root, 'scripts', 'smoke-calendar-width.cjs');
const smokeSmsLogCleanupPath = path.join(root, 'scripts', 'smoke-sms-log-cleanup.cjs');
const smsLogCleanupSqlPath = resolveSqlPath(root, 'sms-module-stage-9-log-cleanup.sql');
const releaseZipPath = path.join(root, 'scripts', 'release-zip.cjs');
const smokeE2eDesktopPath = path.join(root, 'scripts', 'smoke-e2e-desktop.cjs');
const smokeStartupChunkPath = path.join(root, 'scripts', 'smoke-startup-chunk.cjs');
const smokeSupabaseGrantsPath = path.join(root, 'scripts', 'smoke-supabase-grants.cjs');
const smokeAssignmentPushPath = path.join(root, 'scripts', 'smoke-assignment-push.cjs');
const smokeJobDeviceTypeSwitchPath = path.join(root, 'scripts', 'smoke-job-device-type-switch.cjs');
const smokeJobDeviceSpacesPath = path.join(root, 'scripts', 'smoke-job-device-spaces.cjs');
const smokeMobilePrivatePhotosPath = path.join(root, 'scripts', 'smoke-mobile-private-photos.cjs');
const smokeMobilePhotoVisibilitySyncPath = path.join(root, 'scripts', 'smoke-mobile-photo-visibility-sync.cjs');
const smokePhotoCrossDeviceSyncPath = path.join(root, 'scripts', 'smoke-photo-cross-device-sync.cjs');
const smokeMobilePhotoSyncIndicatorPath = path.join(root, 'scripts', 'smoke-mobile-photo-sync-indicator.cjs');
const smokeE2eMobilePath = path.join(root, 'scripts', 'smoke-e2e-mobile.cjs');
const mobilePlaywrightRunnerPath = path.join(root, 'scripts', 'run-playwright-mobile.cjs');
const mobileE2eSpecPath = path.join(root, 'tests', 'e2e', 'mobile-photo-two-sessions.spec.js');
const mobileResilienceE2ePath = path.join(root, 'tests', 'e2e', 'mobile-resilience.spec.js');
const mobilePhotoSyncHookPath = path.join(root, 'src', 'mobile791', 'hooks', 'usePhotoSyncStatus.js');
const mobilePhotoSyncComponentPath = path.join(root, 'src', 'mobile791', 'components', 'PhotoSyncStatus.jsx');
const smokeMobileSerialScannerPath = path.join(root, 'scripts', 'smoke-mobile-serial-scanner.cjs');
const mobileNameplateCapturePath = path.join(root, 'src', 'mobile791', 'components', 'nameplate', 'NameplatePhotoCapture.jsx');
const mobileNameplateCaptureStylesPath = path.join(root, 'src', 'mobile791', 'components', 'nameplate', 'nameplate-photo-capture.css');
const mobileJobFormModalPath = path.join(root, 'src', 'mobile791', 'components', 'modals', 'JobFormModal.jsx');
const mobileDeviceWizardPath = path.join(root, 'src', 'mobile791', 'components', 'devices', 'MobileDeviceWizard.jsx');
const mobileDeviceWizardStylesPath = path.join(root, 'src', 'mobile791', 'components', 'devices', 'mobile-device-wizard.css');
const mobileJobsFormPath = path.join(root, 'src', 'mobile791', 'modules', 'jobs-form.js');
const mobileJobDevicesPath = path.join(root, 'src', 'mobile791', 'modules', 'job-devices.js');
const mobilePhotosPath = path.join(root, 'src', 'mobile791', 'modules', 'photos.js');
const mobileSelectedJobActionsPath = path.join(root, 'src', 'mobile791', 'hooks', 'useSelectedJobActions.js');
const mobileJobDetailsPath = path.join(root, 'src', 'mobile791', 'components', 'JobDetailsPanel.jsx');
const mobileProtocolEmailPath = path.join(root, 'src', 'mobile791', 'modules', 'job-protocol-email.js');
const protocolEmailFunctionPath = path.join(root, 'supabase', 'functions', 'send-job-protocol-email', 'index.ts');
const protocolEmailSetupPath = path.join(root, 'supabase', 'setup-job-protocol-email-v9.87.sql');
const protocolEmailDeployGuidePath = path.join(root, 'SUPABASE-EDGE-DEPLOY-v9.87.md');
const mobileStylesPath = path.join(root, 'src', 'mobile791', 'styles.css');
const mobileSerialE2ePath = path.join(root, 'tests', 'e2e', 'mobile-serial-scanner.spec.js');
const mobileMockSupabasePath = path.join(root, 'src', 'mobile791', 'lib', 'mockSupabaseClient.js');
const verifyBundleBudgetPath = path.join(root, 'scripts', 'verify-bundle-budget.cjs');
const releaseResultWriterPath = path.join(root, 'scripts', 'write-release-result.cjs');
const releaseResultPath = path.join(root, 'RELEASE-RESULT.md');
const desktopReleaseWorkflowPath = path.join(root, '.github', 'workflows', 'desktop-release-checks.yml');
const mobileReleaseWorkflowPath = path.join(root, '.github', 'workflows', 'mobile-release-checks.yml');
const smokeMobileCiWorkflowPath = path.join(root, 'scripts', 'smoke-mobile-ci-workflow.cjs');
const mockSupabaseClientPath = path.join(root, 'src', 'lib', 'mockSupabaseClient.js');
const playwrightConfigPath = path.join(root, 'playwright.config.js');
const desktopE2eSpecPath = path.join(root, 'tests', 'e2e', 'desktop-app.spec.js');
const srcVersionPath = path.join(root, 'src', 'version.js');
const mobileSrcVersionPath = path.join(root, 'src', 'mobile791', 'version.js');
const jobDetailsPath = path.join(root, 'src', 'components', 'JobDetailsPanel.jsx');
const desktopNameplateOcrComponentPath = path.join(root, 'src', 'components', 'desktop', 'DesktopNameplateOcrButton.jsx');
const desktopJobDeviceCardsPath = path.join(root, 'src', 'components', 'desktop', 'DesktopJobDeviceCards.jsx');
const desktopNameplateReaderUtilsPath = path.join(root, 'src', 'modules', 'desktop-nameplate-reader-utils.js');
const desktopNameplateOcrSavePath = path.join(root, 'src', 'modules', 'desktop-nameplate-ocr-save.js');
const desktopNameplateModelDictionaryPath = path.join(root, 'src', 'modules', 'desktop-nameplate-model-dictionary.js');
const desktopNameplateModelOcrPath = path.join(root, 'src', 'modules', 'desktop-nameplate-model-ocr.js');
const smokeDesktopNameplateOcrPath = path.join(root, 'scripts', 'smoke-desktop-nameplate-ocr.cjs');
const smokeDesktopNameplateAutomaticFallbackPath = path.join(root, 'scripts', 'smoke-desktop-nameplate-automatic-fallback.cjs');
const smokeDesktopNameplateEanSeparationPath = path.join(root, 'scripts', 'smoke-desktop-nameplate-ean-separation.cjs');
const desktopNameplateBarcodeModulePath = path.join(root, 'src', 'modules', 'desktop-nameplate-barcode.js');
const desktopNameplateFallbackFixturePath = path.join(root, 'tests', 'fixtures', 'rotenso-revio-ro35xi-r14-nameplate.png');
const dbRepairPostMigrationsPath = resolveSqlPath(root, 'db-repair-production-post-migrations.sql');
const dbHealthCheckPath = resolveSqlPath(root, 'db-health-check.sql');
const dbHealthCheckDetailsPath = resolveSqlPath(root, 'db-health-check-details.sql');
const supabaseGrantsAuditPath = resolveSqlPath(root, 'supabase-grants-audit-wawis.sql');
const releasesDir = path.join(root, 'releases');
const distPath = path.join(root, 'dist');
const {
  getNextVersion,
  updateReadmeVersionMetadata,
  ensureChangelogVersionEntry,
} = require(path.join(root, 'version-bump.cjs'));

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

function extractReadmeCurrentVersion(readme) {
  const match = readme.match(/## Aktualna wersja\s*-\s*([0-9]+\.[0-9]{2})/m);
  return String(match?.[1] || '').trim();
}

function extractReadmeLastFixVersion(readme) {
  const match = readme.match(/## Ostatnia poprawka\s*- wersja\s*`?([0-9]+\.[0-9]{2})`?/m);
  return String(match?.[1] || '').trim();
}

function extractReadmeLastFixBody(readme) {
  const match = readme.match(/## Ostatnia poprawka\s*- wersja\s*`?[0-9]+\.[0-9]{2}`?\s*[—-]\s*(.+)/m);
  return String(match?.[1] || '').trim();
}

function extractReleaseResultVersion(releaseResult) {
  const match = releaseResult.match(/## Wersja\s*-\s*([0-9]+\.[0-9]{2})/m);
  return String(match?.[1] || '').trim();
}

function getChangelogSection(changelog, version) {
  const escapedVersion = version.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const regex = new RegExp(`^## ${escapedVersion}\\r?\\n([\\s\\S]*?)(?=^##\\s|(?![\\s\\S]))`, 'm');
  const match = changelog.match(regex);
  return String(match?.[1] || '').trim();
}

function verifyAutomaticDocInsertion(readme, changelog, version) {
  const nextVersion = getNextVersion(version);
  const simulatedReadme = updateReadmeVersionMetadata(readme, nextVersion);
  const simulatedChangelog = ensureChangelogVersionEntry(changelog, nextVersion);
  const simulatedReadmeCurrent = extractReadmeCurrentVersion(simulatedReadme);
  const simulatedReadmeLastFix = extractReadmeLastFixVersion(simulatedReadme);
  const simulatedReadmeLastFixBody = extractReadmeLastFixBody(simulatedReadme);
  const simulatedChangelogSection = getChangelogSection(simulatedChangelog, nextVersion);

  assert(simulatedReadmeCurrent === nextVersion, 'Automatyczne podbicie nie aktualizuje sekcji Aktualna wersja');
  assert(simulatedReadmeLastFix === nextVersion, 'Automatyczne podbicie nie aktualizuje sekcji Ostatnia poprawka');
  assert(simulatedReadmeLastFixBody.includes('uzupełnij opis ostatniej poprawki'), 'Automatyczne podbicie nie dodaje placeholdera w README.md');
  assert(simulatedChangelogSection.includes('uzupełnij opis zmian dla wersji'), 'Automatyczne podbicie nie dodaje placeholdera w CHANGELOG.md');
}

function hasFiles(directory) {
  if (!fs.existsSync(directory)) return false;
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const entryPath = path.join(directory, entry.name);
    if (entry.isFile()) return true;
    if (entry.isDirectory() && hasFiles(entryPath)) return true;
  }
  return false;
}

function getPartialDistReason() {
  if (!fs.existsSync(distPath)) return '';
  const stats = fs.statSync(distPath);
  if (!stats.isDirectory()) return 'dist istnieje, ale nie jest katalogiem';

  const indexPath = path.join(distPath, 'index.html');
  const assetsPath = path.join(distPath, 'assets');

  if (!fs.existsSync(indexPath) || !fs.statSync(indexPath).isFile()) {
    return 'brakuje dist/index.html';
  }

  if (!fs.existsSync(assetsPath) || !fs.statSync(assetsPath).isDirectory() || !hasFiles(assetsPath)) {
    return 'brakuje plików w dist/assets';
  }

  return '';
}

const requireZip = process.argv.includes('--require-zip');
const appVersion = String(readJson(appVersionPath).version || '').trim();
const packageJson = readJson(packagePath);
const packageVersion = String(packageJson.version || '').trim();
const packageScripts = packageJson.scripts || {};
const packageLock = readJson(packageLockPath);
const packageLockVersion = String(packageLock.version || '').trim();
const packageLockRootVersion = String(packageLock.packages?.['']?.version || '').trim();
const readme = fs.readFileSync(readmePath, 'utf8');
const changelog = fs.readFileSync(changelogPath, 'utf8');
const releaseChecklist = fs.existsSync(releaseChecklistPath) ? fs.readFileSync(releaseChecklistPath, 'utf8') : '';
const releaseResult = fs.existsSync(releaseResultPath) ? fs.readFileSync(releaseResultPath, 'utf8') : '';
const srcVersionSource = fs.readFileSync(srcVersionPath, 'utf8');
const mobileSrcVersionSource = fs.readFileSync(mobileSrcVersionPath, 'utf8');
const readmeCurrentVersion = extractReadmeCurrentVersion(readme);
const readmeLastFixVersion = extractReadmeLastFixVersion(readme);
const readmeLastFixBody = extractReadmeLastFixBody(readme);
const changelogSection = getChangelogSection(changelog, appVersion);
const srcVersionMatch = srcVersionSource.match(/APP_VERSION\s*=\s*['"]([0-9]+\.[0-9]{2})['"]/);
const srcVersion = String(srcVersionMatch?.[1] || '').trim();
const mobileSrcVersionMatch = mobileSrcVersionSource.match(/APP_VERSION\s*=\s*['"]([0-9]+\.[0-9]{2})['"]/);
const mobileSrcVersion = String(mobileSrcVersionMatch?.[1] || '').trim();
const releaseResultVersion = extractReleaseResultVersion(releaseResult);
const partialDistReason = getPartialDistReason();

assert(!partialDistReason, `Wykryto częściowy katalog dist po nieudanym buildzie: ${partialDistReason}. Usuń dist i uruchom build ponownie.`);
assert(appVersion, 'Brak wersji w app-version.json');
assert(packageVersion, 'Brak wersji w package.json');
assert(fs.existsSync(packageLockPath), 'Brak package-lock.json');
assert(fs.existsSync(npmrcPath), 'Brak projektowego pliku .npmrc');
assert(appVersion === packageVersion, `Niezgodność wersji: app-version.json=${appVersion}, package.json=${packageVersion}`);
assert(packageLockVersion === appVersion, `Niezgodność wersji: package-lock.json=${packageLockVersion || 'brak'}, app-version.json=${appVersion}`);
assert(packageLockRootVersion === appVersion, `Niezgodność wersji: package-lock.json packages['']=${packageLockRootVersion || 'brak'}, app-version.json=${appVersion}`);
assert(srcVersion === appVersion, `Niezgodność wersji: src/version.js=${srcVersion || 'brak'}, app-version.json=${appVersion}`);
assert(mobileSrcVersion === appVersion, `Niezgodność wersji mobile: src/mobile791/version.js=${mobileSrcVersion || 'brak'}, app-version.json=${appVersion}`);
assert(fs.existsSync(releaseResultPath), 'Brak pliku RELEASE-RESULT.md');
assert(releaseResultVersion === appVersion, `RELEASE-RESULT.md ma inną wersję: ${releaseResultVersion || 'brak'}, app-version.json=${appVersion}`);
assert(readme.includes(appVersion), `README.md nie zawiera wersji ${appVersion}`);
assert(readmeCurrentVersion === appVersion, `README.md ma inną 'Aktualną wersję': ${readmeCurrentVersion || 'brak'}`);
assert(readmeLastFixVersion === appVersion, `README.md ma inną wersję w sekcji 'Ostatnia poprawka': ${readmeLastFixVersion || 'brak'}`);
assert(readmeLastFixBody.length > 0, `README.md ma pusty opis w sekcji 'Ostatnia poprawka' dla wersji ${appVersion}`);
assert(!/uzupełnij opis ostatniej poprawki/i.test(readmeLastFixBody), `README.md nadal ma placeholder w sekcji 'Ostatnia poprawka' dla wersji ${appVersion}`);
assert(changelog.includes(`## ${appVersion}`), `CHANGELOG.md nie zawiera sekcji dla wersji ${appVersion}`);
assert(changelogSection.length > 0, `Sekcja CHANGELOG dla wersji ${appVersion} jest pusta`);
assert(/^\-\s+/m.test(changelogSection), `Sekcja CHANGELOG dla wersji ${appVersion} nie zawiera listy zmian`);
assert(!new RegExp(`uzupełnij opis zmian dla wersji ${appVersion}`, 'i').test(changelogSection), `CHANGELOG.md nadal ma placeholder dla wersji ${appVersion}`);
assert(fs.existsSync(dbRepairPostMigrationsPath), 'Brak pliku db-repair-production-post-migrations.sql');
assert(fs.existsSync(dbHealthCheckPath), 'Brak pliku db-health-check.sql');
assert(fs.existsSync(dbHealthCheckDetailsPath), 'Brak pliku db-health-check-details.sql');
assert(fs.existsSync(supabaseGrantsAuditPath), 'Brak pliku supabase-grants-audit-wawis.sql');
assert(readme.includes('## Naprawa produkcyjnej bazy po migracjach'), 'README.md nie zawiera sekcji naprawy produkcyjnej bazy po migracjach');
assert(readme.includes('db-repair-production-post-migrations.sql'), 'README.md nie opisuje pliku db-repair-production-post-migrations.sql');
assert(readme.includes('## Diagnostyka produkcyjnej bazy bez zmian'), 'README.md nie zawiera sekcji diagnostyki produkcyjnej bazy bez zmian');
assert(readme.includes('db-health-check.sql'), 'README.md nie opisuje pliku db-health-check.sql');
assert(readme.includes('db-health-check-details.sql'), 'README.md nie opisuje pliku db-health-check-details.sql');
assert(readme.includes('suggested_fix'), 'README.md nie opisuje kolumny suggested_fix w szczegółowej diagnostyce bazy');
assert(readme.includes('test:smoke:version'), 'README.md nie opisuje testu test:smoke:version');
assert(readme.includes('test:smoke:delete'), 'README.md nie opisuje testu test:smoke:delete');
assert(readme.includes('test:smoke:device-save'), 'README.md nie opisuje testu test:smoke:device-save');
assert(readme.includes('test:smoke:device-client-fallback'), 'README.md nie opisuje testu test:smoke:device-client-fallback');
assert(readme.includes('test:smoke:job-contractor-link'), 'README.md nie opisuje testu test:smoke:job-contractor-link');
assert(readme.includes('test:smoke:assignment-push'), 'README.md nie opisuje testu test:smoke:assignment-push');
assert(readme.includes('test:smoke:sms-summary'), 'README.md nie opisuje testu test:smoke:sms-summary');
assert(readme.includes('test:smoke:sms-job-grouping'), 'README.md nie opisuje testu test:smoke:sms-job-grouping');
assert(readme.includes('test:smoke:sms-log-cleanup'), 'README.md nie opisuje testu test:smoke:sms-log-cleanup');
assert(readme.includes('admin_cleanup_sms_duplicate_logs'), 'README.md nie opisuje czyszczenia duplikatów logów SMS');
assert(readme.includes('test:smoke:desktop-refresh'), 'README.md nie opisuje testu test:smoke:desktop-refresh');
assert(readme.includes('test:smoke:desktop-only'), 'README.md nie opisuje testu test:smoke:desktop-only');
assert(readme.includes('test:smoke:desktop-nameplate-ocr'), 'README.md nie opisuje testu test:smoke:desktop-nameplate-ocr');
assert(readme.includes('test:smoke:release-runner'), 'README.md nie opisuje testu test:smoke:release-runner');
assert(readme.includes('test:smoke:windows-npm-runner'), 'README.md nie opisuje testu test:smoke:windows-npm-runner');
assert(readme.includes('test:smoke:release-zip'), 'README.md nie opisuje testu test:smoke:release-zip');
assert(readme.includes('test:smoke:release-zip-clean'), 'README.md nie opisuje testu test:smoke:release-zip-clean');
assert(readme.includes('test:smoke:job-device-type-switch'), 'README.md nie opisuje testu test:smoke:job-device-type-switch');
assert(readme.includes('test:smoke:job-device-spaces'), 'README.md nie opisuje testu test:smoke:job-device-spaces');
assert(readme.includes('test:smoke:supabase-grants'), 'README.md nie opisuje testu test:smoke:supabase-grants');
assert(readme.includes('supabase-grants-audit-wawis.sql'), 'README.md nie opisuje pliku supabase-grants-audit-wawis.sql');
assert(readme.includes('każda nowa tabela') && readme.includes('GRANT'), 'README.md nie opisuje zasady jawnego GRANT dla nowych tabel Supabase');
assert(readme.includes('Zasady pracy z ChatGPT'), 'README.md nie zawiera sekcji Zasady pracy z ChatGPT');
assert(readme.includes('Pracownik: tylko telefon'), 'README.md nie opisuje zasady: Pracownik tylko telefon');
assert(readme.includes('Administrator: desktop i telefon'), 'README.md nie opisuje zasady: Administrator desktop i telefon');
assert(readme.includes('Wróć do kalendarza'), 'README.md nie opisuje przycisku Wróć do kalendarza');
assert(readme.includes('test:smoke:sidebar-settings'), 'README.md nie opisuje testu test:smoke:sidebar-settings');
assert(readme.includes('test:smoke:regex-compat'), 'README.md nie opisuje testu test:smoke:regex-compat');
assert(readme.includes('test:smoke:mobile-private-photos'), 'README.md nie opisuje testu test:smoke:mobile-private-photos');
assert(readme.includes('test:smoke:mobile-photo-visibility-sync'), 'README.md nie opisuje testu test:smoke:mobile-photo-visibility-sync');
assert(readme.includes('test:smoke:photo-cross-device-sync'), 'README.md nie opisuje testu test:smoke:photo-cross-device-sync');
assert(readme.includes('test:smoke:mobile-photo-sync-indicator'), 'README.md nie opisuje testu wskaźnika synchronizacji zdjęć');
assert(readme.includes('test:e2e:mobile'), 'README.md nie opisuje mobilnego E2E');
assert(readme.includes('test:smoke:mobile-serial-scanner'), 'README.md nie opisuje testu dokumentacji tabliczek');
assert(readme.includes('OCR nie jest używany'), 'README.md nie opisuje rezygnacji z OCR w aplikacji mobilnej');
assert(readme.includes('zdjęcie tabliczki') && readme.includes('źródłem prawdy'), 'README.md nie opisuje zdjęcia tabliczki jako podstawy dokumentacji');
assert(readme.includes('model i numer seryjny') && readme.includes('opcjonalne'), 'README.md nie opisuje opcjonalnych pól modelu i numeru seryjnego');
assert(readme.includes('nierozłącznie') && readme.includes('JW2'), 'README.md nie opisuje nierozłącznego parowania modeli i numerów JW');
assert(readme.includes('kompaktową pozycję `Tabliczka znamionowa`') && readme.includes('otwiera się dopiero po kliknięciu'), 'README.md nie opisuje kompaktowych pozycji tabliczek JZ/JW');
assert(readme.includes('test:smoke:admin-worker'), 'README.md nie opisuje testu test:smoke:admin-worker');
assert(readme.includes('test:smoke:sms-client-details'), 'README.md nie opisuje testu test:smoke:sms-client-details');
assert(readme.includes('test:smoke:sms-navigation'), 'README.md nie opisuje testu test:smoke:sms-navigation');
assert(readme.includes('test:smoke:sms-street'), 'README.md nie opisuje testu test:smoke:sms-street');
assert(readme.includes('test:smoke:sms-street-sql'), 'README.md nie opisuje testu test:smoke:sms-street-sql');
assert(readme.includes('częściowy katalog `dist`'), 'README.md nie opisuje blokady częściowego katalogu dist');
assert(readme.includes('prepare:deps'), 'README.md nie opisuje skryptu prepare:deps');
assert(readme.includes('npm ci --include=optional'), 'README.md nie opisuje stabilnej instalacji npm ci --include=optional');
assert(readme.includes('RELEASE-CHECKLIST.md'), 'README.md nie odsyła do RELEASE-CHECKLIST.md');
assert(fs.existsSync(releaseChecklistPath), 'Brak pliku RELEASE-CHECKLIST.md');
assert(releaseChecklist.includes('npm run test:smoke:desktop-only'), 'RELEASE-CHECKLIST.md nie zawiera testu test:smoke:desktop-only');
assert(releaseChecklist.includes('npm run test:smoke:release-runner'), 'RELEASE-CHECKLIST.md nie zawiera testu test:smoke:release-runner');
assert(releaseChecklist.includes('npm run test:smoke:windows-npm-runner'), 'RELEASE-CHECKLIST.md nie zawiera testu test:smoke:windows-npm-runner');
assert(releaseChecklist.includes('npm run test:smoke:release-zip'), 'RELEASE-CHECKLIST.md nie zawiera testu test:smoke:release-zip');
assert(releaseChecklist.includes('npm run test:smoke:release-zip-clean'), 'RELEASE-CHECKLIST.md nie zawiera testu test:smoke:release-zip-clean');
assert(releaseChecklist.includes('npm run test:smoke:calendar-width'), 'RELEASE-CHECKLIST.md nie zawiera testu test:smoke:calendar-width');
assert(releaseChecklist.includes('npm run test:smoke:e2e-desktop'), 'RELEASE-CHECKLIST.md nie zawiera testu test:smoke:e2e-desktop');
assert(releaseChecklist.includes('npm run test:smoke:startup-chunk'), 'RELEASE-CHECKLIST.md nie zawiera testu test:smoke:startup-chunk');
assert(releaseChecklist.includes('npm run test:smoke:assignment-push'), 'RELEASE-CHECKLIST.md nie zawiera testu test:smoke:assignment-push');
assert(releaseChecklist.includes('npm run test:smoke:job-device-type-switch'), 'RELEASE-CHECKLIST.md nie zawiera testu test:smoke:job-device-type-switch');
assert(releaseChecklist.includes('npm run test:smoke:job-device-spaces'), 'RELEASE-CHECKLIST.md nie zawiera testu test:smoke:job-device-spaces');
assert(releaseChecklist.includes('npm run test:smoke:supabase-grants'), 'RELEASE-CHECKLIST.md nie zawiera testu test:smoke:supabase-grants');
assert(releaseChecklist.includes('npm run release:mobile'), 'RELEASE-CHECKLIST.md nie opisuje npm run release:mobile');
assert(releaseChecklist.includes('npm run release:mobile:dry-run'), 'RELEASE-CHECKLIST.md nie opisuje npm run release:mobile:dry-run');
assert(releaseChecklist.includes('npm run test:e2e:mobile'), 'RELEASE-CHECKLIST.md nie opisuje test:e2e:mobile');
assert(releaseChecklist.includes('npm run test:smoke:mobile-serial-scanner'), 'RELEASE-CHECKLIST.md nie zawiera smoke dokumentacji tabliczek');
assert(releaseChecklist.includes('OCR nie jest używany') && releaseChecklist.includes('blokadę zakończenia zlecenia') && releaseChecklist.includes('zdjęcia JZ i każdej JW'), 'RELEASE-CHECKLIST.md nie opisuje wymaganych zdjęć tabliczek i blokady zakończenia');
assert(releaseChecklist.includes('każda nowa tabela') && releaseChecklist.includes('GRANT'), 'RELEASE-CHECKLIST.md nie opisuje zasady jawnego GRANT dla nowych tabel Supabase');
assert(releaseChecklist.includes('npm run verify:bundle'), 'RELEASE-CHECKLIST.md nie zawiera verify:bundle');
assert(releaseChecklist.includes('RELEASE-RESULT.md'), 'RELEASE-CHECKLIST.md nie opisuje RELEASE-RESULT.md');
assert(releaseChecklist.includes('npm run test:e2e:desktop'), 'RELEASE-CHECKLIST.md nie opisuje test:e2e:desktop');
assert(releaseChecklist.includes('npm run test:smoke:sms-job-grouping'), 'RELEASE-CHECKLIST.md nie zawiera testu test:smoke:sms-job-grouping');
assert(releaseChecklist.includes('npm run test:smoke:sms-log-cleanup'), 'RELEASE-CHECKLIST.md nie zawiera testu test:smoke:sms-log-cleanup');
assert(releaseChecklist.includes('npm run verify:release'), 'RELEASE-CHECKLIST.md nie zawiera verify:release');
assert(releaseChecklist.includes('npm run build'), 'RELEASE-CHECKLIST.md nie zawiera builda');
assert(releaseChecklist.includes('npm run zip:release'), 'RELEASE-CHECKLIST.md nie zawiera zip:release');
assert(releaseChecklist.includes('node scripts/verify-release.cjs --require-zip'), 'RELEASE-CHECKLIST.md nie zawiera verify-release --require-zip');
assert(releaseChecklist.includes('częściowy katalog `dist`'), 'RELEASE-CHECKLIST.md nie opisuje blokady częściowego katalogu dist');
assert(fs.existsSync(runReleasePath), 'Brak pliku scripts/run-release.cjs');
assert(fs.existsSync(smokeReleaseRunnerPath), 'Brak pliku scripts/smoke-release-runner.cjs');
assert(fs.existsSync(ensureBuildDepsPath), 'Brak pliku scripts/ensure-build-deps.cjs');
assert(fs.existsSync(smokeWindowsNpmRunnerPath), 'Brak pliku scripts/smoke-windows-npm-runner.cjs');
assert(fs.existsSync(smokeReleaseZipPath), 'Brak pliku scripts/smoke-release-zip.cjs');
assert(fs.existsSync(smokeReleaseZipCleanPath), 'Brak pliku scripts/smoke-release-zip-clean.cjs');
assert(fs.existsSync(smokeCalendarWidthPath), 'Brak pliku scripts/smoke-calendar-width.cjs');
assert(fs.existsSync(smokeSmsLogCleanupPath), 'Brak pliku scripts/smoke-sms-log-cleanup.cjs');
assert(fs.existsSync(smokeE2eDesktopPath), 'Brak pliku scripts/smoke-e2e-desktop.cjs');
assert(fs.existsSync(smokeStartupChunkPath), 'Brak pliku scripts/smoke-startup-chunk.cjs');
assert(fs.existsSync(smokeSupabaseGrantsPath), 'Brak pliku scripts/smoke-supabase-grants.cjs');
assert(fs.existsSync(smokeAssignmentPushPath), 'Brak pliku scripts/smoke-assignment-push.cjs');
assert(fs.existsSync(smokeJobDeviceTypeSwitchPath), 'Brak pliku scripts/smoke-job-device-type-switch.cjs');
assert(fs.existsSync(smokeJobDeviceSpacesPath), 'Brak pliku scripts/smoke-job-device-spaces.cjs');
assert(fs.existsSync(smokeMobilePrivatePhotosPath), 'Brak pliku scripts/smoke-mobile-private-photos.cjs');
assert(fs.existsSync(smokeMobilePhotoVisibilitySyncPath), 'Brak pliku scripts/smoke-mobile-photo-visibility-sync.cjs');
assert(fs.existsSync(smokePhotoCrossDeviceSyncPath), 'Brak pliku scripts/smoke-photo-cross-device-sync.cjs');
assert(fs.existsSync(smokeMobilePhotoSyncIndicatorPath), 'Brak smoke wskaźnika synchronizacji zdjęć');
assert(fs.existsSync(smokeE2eMobilePath), 'Brak smoke mobilnego E2E');
assert(fs.existsSync(mobilePlaywrightRunnerPath), 'Brak runnera Playwright mobile');
assert(fs.existsSync(mobileE2eSpecPath), 'Brak specyfikacji E2E dwóch sesji mobilnych');
assert(fs.existsSync(mobilePhotoSyncHookPath), 'Brak hooka jakości połączenia i synchronizacji zdjęć');
assert(fs.existsSync(mobilePhotoSyncComponentPath), 'Brak komponentu statusu synchronizacji zdjęć');
assert(fs.existsSync(smokeMobileSerialScannerPath), 'Brak smoke dokumentacji tabliczek');
assert(fs.existsSync(mobileNameplateCapturePath), 'Brak mobilnego komponentu zdjęcia tabliczki');
assert(fs.existsSync(mobileNameplateCaptureStylesPath), 'Brak stylów komponentu zdjęcia tabliczki');
assert(fs.existsSync(mobileDeviceWizardPath), 'Brak uproszczonego mobilnego kreatora urządzeń');
assert(fs.existsSync(mobileDeviceWizardStylesPath), 'Brak stylów uproszczonego kreatora urządzeń');
assert(fs.existsSync(mobileJobDevicesPath), 'Brak mobilnej obsługi modeli osobno dla JW/JZ');
assert(fs.existsSync(mobilePhotosPath), 'Brak mobilnego modułu zdjęć');
assert(fs.existsSync(mobileSelectedJobActionsPath), 'Brak mobilnej obsługi zapisu dokumentacji montażu');
assert(fs.existsSync(mobileJobDetailsPath), 'Brak mobilnego panelu dokumentacji montażu');
assert(fs.existsSync(mobileStylesPath), 'Brak stylów aplikacji mobilnej');
assert(fs.existsSync(mobileSerialE2ePath), 'Brak E2E mobilnej dokumentacji tabliczek');
assert(fs.existsSync(mobileMockSupabasePath), 'Brak mobilnych danych testowych Supabase');
assert(fs.existsSync(desktopNameplateOcrComponentPath), 'Brak desktopowego komponentu odczytu tabliczek');
assert(fs.existsSync(desktopNameplateReaderUtilsPath), 'Brak desktopowych narzędzi odczytu tabliczek');
assert(fs.existsSync(desktopNameplateOcrSavePath), 'Brak desktopowego modułu zapisu danych tabliczki');
assert(fs.existsSync(desktopNameplateModelDictionaryPath), 'Brak desktopowego słownika modeli tabliczek');
assert(fs.existsSync(desktopNameplateModelOcrPath), 'Brak lokalnego odczytu nadrukowanego kodu modelu');
assert(fs.existsSync(smokeDesktopNameplateOcrPath), 'Brak testu desktopowego odczytu tabliczek');
assert(!fs.existsSync(path.join(root, 'src', 'modules', 'desktop-nameplate-ocr.js')), 'Stary szeroki OCR desktop nadal istnieje');
assert(fs.existsSync(path.join(root, 'public', 'ocr', 'eng.traineddata.gz')), 'Brak lokalnych zasobów odczytu modelu');
assert(fs.existsSync(smokeDesktopNameplateAutomaticFallbackPath), 'Brak testu automatycznego fallbacku PC/EAN i SN');
assert(fs.existsSync(smokeDesktopNameplateEanSeparationPath), 'Brak testu rozdzielenia PC/EAN od SN i zgodności JW/JZ');
assert(fs.existsSync(desktopNameplateFallbackFixturePath), 'Brak zdjęcia regresyjnego RO35Xi R14 dla odczytu tabliczki');
assert(packageScripts['test:smoke:desktop-nameplate-automatic-fallback'] === 'node scripts/smoke-desktop-nameplate-automatic-fallback.cjs', 'package.json nie zawiera testu automatycznego fallbacku tabliczki');
assert(packageScripts['test:smoke:desktop-nameplate-ean-separation'] === 'node scripts/smoke-desktop-nameplate-ean-separation.cjs', 'package.json nie zawiera testu rozdzielenia PC/EAN od SN');
assert(!fs.existsSync(path.join(root, 'src', 'mobile791', 'modules', 'serial-number-ocr.js')), 'Mobilny moduł OCR nadal istnieje');
assert(fs.existsSync(verifyBundleBudgetPath), 'Brak pliku scripts/verify-bundle-budget.cjs');
assert(fs.existsSync(releaseResultWriterPath), 'Brak pliku scripts/write-release-result.cjs');
assert(fs.existsSync(mockSupabaseClientPath), 'Brak pliku src/lib/mockSupabaseClient.js');
assert(fs.existsSync(playwrightConfigPath), 'Brak pliku playwright.config.js');
assert(fs.existsSync(desktopE2eSpecPath), 'Brak pliku tests/e2e/desktop-app.spec.js');
assert(fs.existsSync(mobileResilienceE2ePath), 'Brak pliku tests/e2e/mobile-resilience.spec.js');
assert(!fs.existsSync(path.join(root, 'tests', 'e2e', 'desktop-visual.spec.js')), 'Osierocony desktop-visual.spec.js powinien być usunięty');
assert(fs.existsSync(smsLogCleanupSqlPath), 'Brak pliku sms-module-stage-9-log-cleanup.sql');
assert(fs.existsSync(releaseZipPath), 'Brak pliku scripts/release-zip.cjs');
assert(packageScripts.release === 'node scripts/run-release.cjs full', 'package.json nie przenosi release do scripts/run-release.cjs full');
assert(packageScripts['release:mobile'] === 'node scripts/run-release.cjs mobile', 'package.json nie zawiera release:mobile');
assert(packageScripts['release:mobile:dry-run'] === 'node scripts/run-release.cjs mobile --dry-run', 'package.json nie zawiera release:mobile:dry-run');
assert(packageScripts['release:desktop'] === 'node scripts/run-release.cjs desktop', 'package.json nie zawiera release:desktop dla desktopowej checklisty');
assert(packageScripts['release:desktop:dry-run'] === 'node scripts/run-release.cjs desktop --dry-run', 'package.json nie zawiera release:desktop:dry-run');
assert(packageScripts['release:desktop:sandbox'] === 'node scripts/run-release.cjs desktop-sandbox', 'package.json nie zawiera release:desktop:sandbox');
assert(packageScripts['test:smoke:release-runner'] === 'node scripts/smoke-release-runner.cjs', 'package.json nie zawiera test:smoke:release-runner');
assert(packageScripts['test:smoke:windows-npm-runner'] === 'node scripts/smoke-windows-npm-runner.cjs', 'package.json nie zawiera test:smoke:windows-npm-runner');
assert(fs.existsSync(smokeNpmRegistryPath), 'Brak pliku scripts/smoke-npm-registry.cjs');
assert(packageScripts['test:smoke:npm-registry'] === 'node scripts/smoke-npm-registry.cjs', 'package.json nie zawiera test:smoke:npm-registry');
assert(packageScripts['test:smoke:release-zip'] === 'node scripts/smoke-release-zip.cjs', 'package.json nie zawiera test:smoke:release-zip');
assert(packageScripts['test:smoke:release-zip-clean'] === 'node scripts/smoke-release-zip-clean.cjs', 'package.json nie zawiera test:smoke:release-zip-clean');
assert(packageScripts['test:smoke:calendar-width'] === 'node scripts/smoke-calendar-width.cjs', 'package.json nie zawiera test:smoke:calendar-width');
assert(packageScripts['test:smoke:sms-job-grouping'] === 'node scripts/smoke-sms-job-grouping.cjs', 'package.json nie zawiera test:smoke:sms-job-grouping');
assert(packageScripts['test:smoke:sms-log-cleanup'] === 'node scripts/smoke-sms-log-cleanup.cjs', 'package.json nie zawiera test:smoke:sms-log-cleanup');
assert(packageScripts['test:smoke:e2e-desktop'] === 'node scripts/smoke-e2e-desktop.cjs', 'package.json nie zawiera test:smoke:e2e-desktop');
assert(packageScripts['test:smoke:startup-chunk'] === 'node scripts/smoke-startup-chunk.cjs', 'package.json nie zawiera test:smoke:startup-chunk');
assert(packageScripts['test:smoke:supabase-grants'] === 'node scripts/smoke-supabase-grants.cjs', 'package.json nie zawiera test:smoke:supabase-grants');
assert(packageScripts['test:smoke:assignment-push'] === 'node scripts/smoke-assignment-push.cjs', 'package.json nie zawiera test:smoke:assignment-push');
assert(packageScripts['test:smoke:job-device-type-switch'] === 'node scripts/smoke-job-device-type-switch.cjs', 'package.json nie zawiera test:smoke:job-device-type-switch');
assert(packageScripts['test:smoke:job-device-spaces'] === 'node scripts/smoke-job-device-spaces.cjs', 'package.json nie zawiera test:smoke:job-device-spaces');
assert(packageScripts['test:smoke:mobile-private-photos'] === 'node scripts/smoke-mobile-private-photos.cjs', 'package.json nie zawiera test:smoke:mobile-private-photos');
assert(packageScripts['test:smoke:mobile-photo-visibility-sync'] === 'node scripts/smoke-mobile-photo-visibility-sync.cjs', 'package.json nie zawiera test:smoke:mobile-photo-visibility-sync');
assert(packageScripts['test:smoke:photo-cross-device-sync'] === 'node scripts/smoke-photo-cross-device-sync.cjs', 'package.json nie zawiera test:smoke:photo-cross-device-sync');
assert(packageScripts['test:smoke:mobile-photo-sync-indicator'] === 'node scripts/smoke-mobile-photo-sync-indicator.cjs', 'package.json nie zawiera test:smoke:mobile-photo-sync-indicator');
assert(packageScripts['test:smoke:e2e-mobile'] === 'node scripts/smoke-e2e-mobile.cjs', 'package.json nie zawiera test:smoke:e2e-mobile');
assert(packageScripts['test:e2e:mobile'] === 'node scripts/run-playwright-mobile.cjs', 'package.json nie zawiera test:e2e:mobile');
assert(packageScripts['test:smoke:mobile-ci'] === 'node scripts/smoke-mobile-ci-workflow.cjs', 'package.json nie zawiera test:smoke:mobile-ci');
assert(packageScripts['test:smoke:mobile-serial-scanner'] === 'node scripts/smoke-mobile-serial-scanner.cjs', 'package.json nie zawiera test:smoke:mobile-serial-scanner');
assert(!packageJson.dependencies?.['tesseract.js'], 'package.json nadal zawiera nieużywany silnik OCR tesseract.js');
assert(!packageJson.dependencies?.['@tesseract.js-data/eng'], 'package.json nadal zawiera nieużywane dane OCR');
assert(!packageJson.dependencies?.['@zxing/browser'], 'package.json nadal zawiera nieużywany czytnik kodów kreskowych ZXing');
assert(!packageJson.dependencies?.['@zxing/library'], 'package.json nadal zawiera nieużywaną bibliotekę ZXing');
assert(packageScripts['test:e2e:desktop'] === 'node scripts/run-playwright-desktop.cjs e2e', 'package.json nie zawiera test:e2e:desktop');
assert(!packageScripts['test:visual:desktop'], 'Osierocony test:visual:desktop powinien być usunięty z package.json');
assert(packageScripts['verify:bundle'] === 'node scripts/verify-bundle-budget.cjs', 'package.json nie zawiera verify:bundle');
assert(!packageScripts.release.includes('&&'), 'package.json nadal ma długą komendę release zamiast runnera Node');
assert(readme.includes('npm run release:desktop'), 'README.md nie opisuje npm run release:desktop');
assert(readme.includes('npm run release:mobile'), 'README.md nie opisuje npm run release:mobile');
assert(readme.includes('npm run release:mobile:dry-run'), 'README.md nie opisuje npm run release:mobile:dry-run');
assert(readme.includes('npm run release:desktop:dry-run'), 'README.md nie opisuje npm run release:desktop:dry-run');
assert(readme.includes('npm run release:desktop:sandbox'), 'README.md nie opisuje npm run release:desktop:sandbox');
assert(readme.includes('bez `npm run build` w sandboxie'), 'README.md nie opisuje release bez npm run build w sandboxie');
assert(readme.includes('scripts/run-release.cjs'), 'README.md nie opisuje scripts/run-release.cjs');
assert(readme.includes('.github/workflows/mobile-release-checks.yml'), 'README.md nie opisuje automatycznego workflow mobile');
assert(readme.includes('test:smoke:mobile-ci'), 'README.md nie opisuje testu workflow mobile CI');
assert(readme.includes('ZIELONY') && readme.includes('CZERWONY'), 'README.md nie opisuje zielonego/czerwonego statusu mobile CI');
assert(releaseChecklist.includes('npm run release:desktop'), 'RELEASE-CHECKLIST.md nie opisuje npm run release:desktop');
assert(releaseChecklist.includes('npm run release:desktop:dry-run'), 'RELEASE-CHECKLIST.md nie opisuje npm run release:desktop:dry-run');
assert(releaseChecklist.includes('npm run release:desktop:sandbox'), 'RELEASE-CHECKLIST.md nie opisuje npm run release:desktop:sandbox');
assert(releaseChecklist.includes('bez `npm run build` w sandboxie'), 'RELEASE-CHECKLIST.md nie opisuje trybu sandbox bez builda');
assert(releaseChecklist.includes('scripts/run-release.cjs'), 'RELEASE-CHECKLIST.md nie opisuje scripts/run-release.cjs');
assert(releaseChecklist.includes('mobile-release-checks.yml'), 'RELEASE-CHECKLIST.md nie opisuje automatycznego workflow mobile');
assert(releaseChecklist.includes('test:smoke:mobile-ci'), 'RELEASE-CHECKLIST.md nie zawiera testu workflow mobile CI');
const runReleaseSource = fs.readFileSync(runReleasePath, 'utf8');
const ensureBuildDepsSource = fs.readFileSync(ensureBuildDepsPath, 'utf8');
const releaseResultWriterSource = fs.readFileSync(releaseResultWriterPath, 'utf8');
const desktopReleaseWorkflowSource = fs.existsSync(desktopReleaseWorkflowPath) ? fs.readFileSync(desktopReleaseWorkflowPath, 'utf8') : '';
const mobileReleaseWorkflowSource = fs.existsSync(mobileReleaseWorkflowPath) ? fs.readFileSync(mobileReleaseWorkflowPath, 'utf8') : '';
const releaseZipSource = fs.readFileSync(releaseZipPath, 'utf8');
const smokeReleaseZipSource = fs.readFileSync(smokeReleaseZipPath, 'utf8');
const smokeReleaseZipCleanSource = fs.readFileSync(smokeReleaseZipCleanPath, 'utf8');
const smokeCalendarWidthSource = fs.readFileSync(smokeCalendarWidthPath, 'utf8');
const smokeJobDeviceTypeSwitchSource = fs.readFileSync(smokeJobDeviceTypeSwitchPath, 'utf8');
const smokeJobDeviceSpacesSource = fs.readFileSync(smokeJobDeviceSpacesPath, 'utf8');
const smokeSupabaseGrantsSource = fs.readFileSync(smokeSupabaseGrantsPath, 'utf8');
const supabaseGrantsAuditSource = fs.readFileSync(supabaseGrantsAuditPath, 'utf8');
const jobDetailsSource = fs.readFileSync(jobDetailsPath, 'utf8');
const desktopNameplateOcrComponentSource = fs.readFileSync(desktopNameplateOcrComponentPath, 'utf8');
const desktopJobDeviceCardsSource = fs.readFileSync(desktopJobDeviceCardsPath, 'utf8');
const desktopNameplateReaderUtilsSource = fs.readFileSync(desktopNameplateReaderUtilsPath, 'utf8');
const desktopNameplateOcrSaveSource = fs.readFileSync(desktopNameplateOcrSavePath, 'utf8');
const smokeDesktopNameplateOcrSource = fs.readFileSync(smokeDesktopNameplateOcrPath, 'utf8');
const smokeDesktopNameplateAutomaticFallbackSource = fs.readFileSync(smokeDesktopNameplateAutomaticFallbackPath, 'utf8');
const desktopNameplateBarcodeModuleSource = fs.readFileSync(desktopNameplateBarcodeModulePath, 'utf8');
const mockSupabaseSource = fs.readFileSync(mockSupabaseClientPath, 'utf8');
const playwrightConfigSource = fs.readFileSync(playwrightConfigPath, 'utf8');
const desktopE2eSource = fs.readFileSync(desktopE2eSpecPath, 'utf8');
const mobileNameplateCaptureSource = fs.readFileSync(mobileNameplateCapturePath, 'utf8');
const mobileNameplateCaptureStylesSource = fs.readFileSync(mobileNameplateCaptureStylesPath, 'utf8');
const mobileJobFormModalSource = fs.readFileSync(mobileJobFormModalPath, 'utf8');
const mobileDeviceWizardSource = fs.readFileSync(mobileDeviceWizardPath, 'utf8');
const mobileDeviceWizardStylesSource = fs.readFileSync(mobileDeviceWizardStylesPath, 'utf8');
const mobileJobDevicesSource = fs.readFileSync(mobileJobDevicesPath, 'utf8');
const mobileJobsFormSource = fs.readFileSync(mobileJobsFormPath, 'utf8');
const mobilePhotosSource = fs.readFileSync(mobilePhotosPath, 'utf8');
const mobileSelectedJobActionsSource = fs.readFileSync(mobileSelectedJobActionsPath, 'utf8');
const mobileJobDetailsSource = fs.readFileSync(mobileJobDetailsPath, 'utf8');
const mobileStylesSource = fs.readFileSync(mobileStylesPath, 'utf8');
const mobileSerialE2eSource = fs.readFileSync(mobileSerialE2ePath, 'utf8');
const mobileMockSupabaseSource = fs.readFileSync(mobileMockSupabasePath, 'utf8');
assert(mobileNameplateCaptureSource.includes('capture="environment"'), 'Zdjęcie tabliczki nie otwiera tylnego aparatu');
assert(mobileNameplateCaptureSource.includes('nameplateCameraInput') && mobileNameplateCaptureSource.includes('nameplateGalleryInput'), 'Komponent tabliczki nie rozdziela aparatu i galerii');
assert(mobileNameplateCaptureSource.includes('Tabliczka znamionowa') && mobileNameplateCaptureSource.includes('compact = false'), 'Komponent nie obsługuje kompaktowej pozycji tabliczki z podglądem na żądanie');
assert(!mobileNameplateCaptureSource.includes('scanSerialNumberFromImage') && !mobileNameplateCaptureSource.includes('getUserMedia'), 'Komponent tabliczki nadal uruchamia OCR albo osadzony aparat');
assert(mobileNameplateCaptureStylesSource.includes('.nameplateCapture') && mobileNameplateCaptureStylesSource.includes('.nameplateCapturePreview'), 'Brak kompaktowych stylów zdjęcia tabliczki');
assert(mobileJobFormModalSource.includes('MobileDeviceWizard') && !mobileJobFormModalSource.includes('SerialNumberScanner'), 'Formularz mobilny nie używa uproszczonego kreatora albo nadal używa skanera OCR');
assert(mobileJobFormModalSource.includes('onSetUnitDescriptor') && mobileJobFormModalSource.includes('onAddIndoorUnit') && mobileJobFormModalSource.includes('onAddDevice'), 'Formularz nie podłącza Single/Multi i wielu urządzeń do rzeczywistego zapisu');
assert(!mobileJobFormModalSource.includes('Dodaj wszystkie wymagane zdjęcia tabliczek przed zapisaniem'), 'Formularz nadal blokuje zapis niepełnego zestawu zamiast blokować dopiero zakończenie zlecenia');
assert(mobileDeviceWizardSource.includes('Wybierz markę') && mobileDeviceWizardSource.includes('Wybierz model') && mobileDeviceWizardSource.includes('Wybierz moc'), 'Kreator nie ma kontekstowego wyboru marka/model/moc');
assert(mobileDeviceWizardSource.includes('Single') && mobileDeviceWizardSource.includes('Multi') && mobileDeviceWizardSource.includes('Dodaj kolejne urządzenie') && mobileDeviceWizardSource.includes('+ Dodaj JW'), 'Kreator nie obsługuje Single, Multi, dodatkowej JW i kolejnego urządzenia');
assert(!mobileDeviceWizardSource.includes('Zlecenia nie da się zakończyć bez tabliczki JZ i każdej JW') && mobileDeviceWizardSource.includes('Wszystkie tabliczki dodane') && mobileDeviceWizardSource.includes('tabliczek gotowe'), 'Podsumowanie kreatora nadal powtarza instrukcję albo nie pokazuje krótkiego stanu kompletu tabliczek');
assert(mobileDeviceWizardStylesSource.includes('.mobileDeviceWizard') && mobileDeviceWizardStylesSource.includes('.mobileDevicePickerSheet'), 'Brak stylów prostego kreatora i menu kontekstowego');
assert(mobileJobDevicesSource.includes('parseDeviceModelLine') && mobileJobDevicesSource.includes('formatDeviceModel'), 'Mobilny zapis nie rozdziela modeli JW/JZ');
assert(mobileJobDevicesSource.includes('getDeviceIndoorUnits') && mobileJobDevicesSource.includes('setStructuredIndoorValue'), 'Mobilny zapis nie pilnuje nierozłącznych par JW');
assert(mobileJobDevicesSource.includes('inferJobDevicesFromNameplatePhotos'), 'Widok nie potrafi odtworzyć jednostek ze zdjęć tabliczek');
assert(mobilePhotosSource.includes("NAMEPLATE_PHOTO_FOLDER = 'nameplates'"), 'Zdjęcia tabliczek nie mają osobnego katalogu dokumentacji');
assert(mobilePhotosSource.includes('uploadJobDocumentationPhotos'), 'Brak wysyłki tabliczek do dokumentacji montażu');
assert(mobileSelectedJobActionsSource.includes('uploadJobDocumentationPhotos'), 'Zapis montażu nie uruchamia wysyłki dokumentacji tabliczek');
assert(mobileSelectedJobActionsSource.includes('loadJobNameplatePhotosData') && mobileSelectedJobActionsSource.includes('locallyConfirmedOnServer'), 'Zakończenie zlecenia nie używa lekkiej kontroli tabliczek ani bezpiecznego fallbacku');
assert(mobileJobDetailsSource.includes('nameplateCompletion.isComplete') && mobileJobDetailsSource.includes('disabled={busy || showDetailsLoading || !nameplateCompletion.isComplete}'), 'Przycisk Zakończ nie jest blokowany bez kompletu tabliczek');
assert(mobileSelectedJobActionsSource.includes('openSerialNumbersJob') && mobileSelectedJobActionsSource.includes('saveJobDeviceSerialsRecord'), 'Pracownik nie ma ograniczonej ścieżki zapisu urządzeń i tabliczek');
assert(mobileJobsFormSource.includes('saveJobDeviceSerialsRecord') && mobileJobsFormSource.includes('device_serial_number'), 'Ograniczony zapis pracownika nie aktualizuje pól urządzeń');
assert(mobileJobDetailsSource.includes('DeviceUnitDocumentationRow') && mobileJobDetailsSource.includes('onClick={handleAction}') && mobileJobDetailsSource.includes('Otwórz tabliczkę znamionową'), 'Karta montażu nie pokazuje klikalnych wierszy modelu i tabliczki jednostki');
assert(mobileJobDetailsSource.includes('Urządzenia i tabliczki') && mobileJobDetailsSource.includes('Nie można zakończyć zlecenia') && mobileJobDetailsSource.includes('Dodaj brakujące tabliczki'), 'Karta montażu nie blokuje zakończenia bez dokumentacji JZ/JW');
assert(mobileJobDetailsSource.includes('workerSerialNumbersBtn'), 'Karta montażu nie pokazuje pracownikowi przycisku tabliczek');
assert(mobileJobsFormSource.includes('device_model: deviceFields.device_model'), 'Ograniczony zapis pracownika nie zapisuje modeli JW/JZ');
assert(mobileSerialE2eSource.includes('mobileDeviceWizard') && mobileSerialE2eSource.includes('nameplateGalleryInput'), 'E2E nie sprawdza nowego kreatora i osobnych zdjęć JZ/JW');
assert(mobileJobDevicesSource.includes('setStructuredIndoorValue') && mobileJobsFormSource.includes('indoor_serial_numbers'), 'Kontrola release nie zabezpiecza nierozłącznych danych JW');
assert(mobileSerialE2eSource.includes('deviceUnitDocumentationRow') && mobileSerialE2eSource.includes('toBeDisabled') && mobileSerialE2eSource.includes('toBeEnabled'), 'E2E nie sprawdza czytelnej listy tabliczek i blokady zakończenia');
assert(mobileMockSupabaseSource.includes('klima-mock-supabase-store-v3'), 'Mobilne dane mock nie wymuszają odświeżenia zestawu testowego');
assert(mobileMockSupabaseSource.includes('Klient Testowy Multi-Split') && mobileMockSupabaseSource.includes('JW3: TEST-MULTI-JW-3') && mobileMockSupabaseSource.includes('mock-job-005'), 'Mobilny mock nie zawiera realizacji Multi-Split 3×JW');
assert(mobileMockSupabaseSource.includes('JW1: Rotenso Model JW 1 (TEST)') && mobileMockSupabaseSource.includes('JW3: Rotenso Model JW 3 (TEST)'), 'Mobilny mock Multi-Split nie zawiera osobnych modeli trzech JW');
assert(runReleaseSource.includes('getReleasePlan'), 'scripts/run-release.cjs nie udostępnia getReleasePlan dla smoke testu');
assert(runReleaseSource.includes('--dry-run'), 'scripts/run-release.cjs nie ma trybu --dry-run do sprawdzania planu bez builda');
assert(runReleaseSource.includes('test:smoke:release-runner'), 'scripts/run-release.cjs nie zawiera test:smoke:release-runner w planie release');
assert(runReleaseSource.includes('test:smoke:windows-npm-runner'), 'scripts/run-release.cjs nie zawiera test:smoke:windows-npm-runner w planie release');
assert(ensureBuildDepsSource.includes('process.env.npm_execpath'), 'scripts/ensure-build-deps.cjs nie używa npm_execpath bieżącego procesu npm');
assert(ensureBuildDepsSource.includes("isWindows ? 'npm.cmd' : 'npm'"), 'scripts/ensure-build-deps.cjs nie ma awaryjnego npm.cmd na Windows');
assert(runReleaseSource.includes('test:smoke:release-zip'), 'scripts/run-release.cjs nie zawiera test:smoke:release-zip w planie release');
assert(runReleaseSource.includes('test:smoke:release-zip-clean'), 'scripts/run-release.cjs nie zawiera test:smoke:release-zip-clean w planie release');
assert(runReleaseSource.includes('test:smoke:calendar-width'), 'scripts/run-release.cjs nie zawiera test:smoke:calendar-width w planie release');
assert(runReleaseSource.includes('test:smoke:sms-job-grouping'), 'scripts/run-release.cjs nie zawiera test:smoke:sms-job-grouping w planie release');
assert(runReleaseSource.includes('test:smoke:sms-log-cleanup'), 'scripts/run-release.cjs nie zawiera test:smoke:sms-log-cleanup w planie release');
assert(runReleaseSource.includes('test:smoke:e2e-desktop'), 'scripts/run-release.cjs nie zawiera test:smoke:e2e-desktop w planie release');
assert(runReleaseSource.includes('test:e2e:desktop'), 'scripts/run-release.cjs nie uruchamia prawdziwego desktopowego E2E');
assert(runReleaseSource.includes('test:smoke:destructive-rls'), 'scripts/run-release.cjs nie zawiera testu destrukcyjnych polityk RLS');
assert(runReleaseSource.includes('test:smoke:center360') && runReleaseSource.includes('test:smoke:dashboard-metrics'), 'scripts/run-release.cjs nie zawiera najważniejszych testów Centrum 360');
assert(runReleaseSource.includes('test:smoke:desktop-nameplate-white-screen'), 'scripts/run-release.cjs nie zawiera ochrony przed białym ekranem tabliczki');
assert(runReleaseSource.includes('test:smoke:desktop-nameplate-ai-barcode'), 'scripts/run-release.cjs nie zawiera testu AI/kodów tabliczki');
assert(runReleaseSource.includes('test:smoke:desktop-nameplate-ean-separation'), 'scripts/run-release.cjs nie zawiera testu rozdzielenia PC/EAN od SN');
assert(runReleaseSource.includes('test:smoke:remove-resend-email'), 'scripts/run-release.cjs nie pilnuje usunięcia starego Resend API');
assert(runReleaseSource.includes('test:smoke:mobile-protocol-email'), 'scripts/run-release.cjs nie sprawdza firmowej wysyłki protokołu');
assert(packageScripts['test:smoke:mobile-protocol-email'] === 'node scripts/test-job-protocol-email-v987.mjs', 'Brak testu firmowej wysyłki protokołu');
assert(fs.existsSync(mobileProtocolEmailPath), 'Brak klienta firmowej wysyłki protokołu');
assert(fs.existsSync(protocolEmailFunctionPath), 'Brak Edge Function send-job-protocol-email');
assert(fs.existsSync(protocolEmailSetupPath), 'Brak konfiguracji SQL historii wysyłek protokołu');
assert(fs.existsSync(protocolEmailDeployGuidePath), 'Brak instrukcji uruchomienia firmowej wysyłki protokołu');
assert(runReleaseSource.includes('test:smoke:startup-chunk'), 'scripts/run-release.cjs nie zawiera test:smoke:startup-chunk w planie release');
assert(runReleaseSource.includes('test:smoke:supabase-grants'), 'scripts/run-release.cjs nie zawiera test:smoke:supabase-grants w planie release');
assert(runReleaseSource.includes('test:smoke:assignment-push'), 'scripts/run-release.cjs nie zawiera test:smoke:assignment-push w planie release');
assert(runReleaseSource.includes('test:smoke:job-device-type-switch'), 'scripts/run-release.cjs nie zawiera test:smoke:job-device-type-switch w planie release');
assert(runReleaseSource.includes('test:smoke:job-device-spaces'), 'scripts/run-release.cjs nie zawiera test:smoke:job-device-spaces w planie release');
assert(runReleaseSource.includes('MOBILE_SMOKE_COMMANDS'), 'scripts/run-release.cjs nie zawiera osobnego zestawu mobilnych smoke testów');
assert(runReleaseSource.includes('test:smoke:mobile-private-photos'), 'scripts/run-release.cjs nie zawiera testu prywatnych zdjęć mobile');
assert(runReleaseSource.includes('test:smoke:mobile-photo-visibility-sync'), 'scripts/run-release.cjs nie zawiera testu widoczności zdjęć mobile');
assert(runReleaseSource.includes('test:smoke:photo-cross-device-sync'), 'scripts/run-release.cjs nie zawiera testu synchronizacji zdjęć między urządzeniami');
assert(runReleaseSource.includes('test:smoke:mobile-photo-sync-indicator'), 'scripts/run-release.cjs nie zawiera testu wskaźnika synchronizacji');
assert(runReleaseSource.includes('test:e2e:mobile'), 'scripts/run-release.cjs nie uruchamia prawdziwego mobilnego E2E');
const mobileResilienceE2eSource = fs.readFileSync(mobileResilienceE2ePath, 'utf8');
assert(mobileResilienceE2eSource.includes('wawis-mobile-photo-queue') && mobileResilienceE2eSource.includes('page.reload()'), 'Mobilne E2E nie sprawdza trwałości kolejki zdjęć po restarcie');
assert(mobileResilienceE2eSource.includes('Komentarze i pytania') && mobileResilienceE2eSource.includes('Zakończone · tylko podgląd'), 'Mobilne E2E nie sprawdza pustej sekcji komentarzy zakończonego zlecenia');
assert(runReleaseSource.includes('test:smoke:mobile-serial-scanner'), 'scripts/run-release.cjs nie zawiera testu skanera numerów seryjnych');
assert(runReleaseSource.includes('npm run verify:bundle'), 'scripts/run-release.cjs nie zawiera verify:bundle w planie release');
assert(runReleaseSource.includes('writeReleaseResult'), 'scripts/run-release.cjs nie zapisuje RELEASE-RESULT.md');
assert(runReleaseSource.includes('desktop-sandbox'), 'scripts/run-release.cjs nie obsługuje trybu desktop-sandbox');
assert(runReleaseSource.includes('SANDBOX_BUILD_SKIP_REASON'), 'scripts/run-release.cjs nie opisuje powodu pominięcia builda w sandboxie');
assert(releaseResultWriterSource.includes('POMINIĘTO'), 'write-release-result.cjs nie zapisuje pominiętych kroków w RELEASE-RESULT.md');
assert(desktopReleaseWorkflowSource.includes('npm run release:desktop -- --skip-version-bump'), 'desktop-release-checks.yml nie uruchamia tego samego runnera co release:desktop');
assert(!desktopReleaseWorkflowSource.includes('Smoke pass 1'), 'desktop-release-checks.yml nadal ma ręcznie rozpisane smoke testy zamiast release:desktop');
assert(!fs.existsSync(path.join(root, 'api', 'send-assignment-email.js')), 'Stary endpoint send-assignment-email.js powinien być usunięty');
assert(!fs.existsSync(path.join(root, 'src', 'components', 'services')), 'Martwy katalog modułu Serwisy powinien być usunięty');
assert(!fs.existsSync(path.join(root, 'src', 'modules', 'services-fetch.js')), 'Martwy services-fetch.js powinien być usunięty');
assert(!fs.existsSync(path.join(root, 'scripts', 'smoke-services-module.cjs')), 'Sprzeczny smoke-services-module.cjs powinien być usunięty');
assert(!fs.existsSync(path.join(root, 'scripts', 'smoke-release-zip-exclusions.cjs')), 'Zastąpiony smoke-release-zip-exclusions.cjs powinien być usunięty');
assert(!fs.existsSync(path.join(root, 'scripts', 'smoke-desktop-ocr-crop-ui.cjs')), 'Osierocony smoke-desktop-ocr-crop-ui.cjs powinien być usunięty');
assert(!fs.existsSync(path.join(root, 'scripts', 'smoke-desktop-ocr-mouse-crop.cjs')), 'Osierocony smoke-desktop-ocr-mouse-crop.cjs powinien być usunięty');
assert(!packageScripts['test:smoke:roles'], 'Zdublowany alias test:smoke:roles powinien być usunięty');
const fixtureDirectoryPath = path.join(root, 'tests', 'fixtures');
const allowedRegressionFixtures = new Set(['rotenso-revio-ro35xi-r14-nameplate.png']);
const unexpectedRegressionFixtures = fs.existsSync(fixtureDirectoryPath)
  ? fs.readdirSync(fixtureDirectoryPath).filter((name) => !allowedRegressionFixtures.has(name))
  : [];
assert(unexpectedRegressionFixtures.length === 0, `Katalog tests/fixtures zawiera nieużywane pliki: ${unexpectedRegressionFixtures.join(', ')}`);
assert(fs.existsSync(mobileReleaseWorkflowPath), 'Brak .github/workflows/mobile-release-checks.yml');
assert(fs.existsSync(smokeMobileCiWorkflowPath), 'Brak scripts/smoke-mobile-ci-workflow.cjs');
assert(mobileReleaseWorkflowSource.includes('npm run release:mobile -- --skip-version-bump'), 'mobile-release-checks.yml nie uruchamia tego samego runnera co release:mobile');
assert(mobileReleaseWorkflowSource.includes('npm ci --include=optional --registry=https://registry.npmjs.org/'), 'mobile-release-checks.yml nie instaluje zależności z publicznego npm');
assert(mobileReleaseWorkflowSource.includes('npx playwright install --with-deps chromium'), 'mobile-release-checks.yml nie instaluje Chromium dla Playwright');
assert(mobileReleaseWorkflowSource.includes('releases/klima-app-v${{ steps.app-version.outputs.version }}.zip'), 'mobile-release-checks.yml nie publikuje zweryfikowanego ZIP-a');
assert(mobileReleaseWorkflowSource.includes('path: RELEASE-RESULT.md'), 'mobile-release-checks.yml nie publikuje raportu wydania');
assert(mobileReleaseWorkflowSource.includes('GITHUB_STEP_SUMMARY') && mobileReleaseWorkflowSource.includes('ZIELONY') && mobileReleaseWorkflowSource.includes('CZERWONY'), 'mobile-release-checks.yml nie publikuje zielonego/czerwonego podsumowania');
assert(runReleaseSource.includes('test:smoke:mobile-ci'), 'scripts/run-release.cjs nie zawiera testu workflow mobile CI');
const smsLogCleanupSqlSource = fs.readFileSync(smsLogCleanupSqlPath, 'utf8');
assert(smsLogCleanupSqlSource.includes('admin_cleanup_sms_duplicate_logs'), 'SQL nie tworzy funkcji admin_cleanup_sms_duplicate_logs');
assert(smsLogCleanupSqlSource.includes('delete from public.sms_log'), 'SQL nie usuwa duplikatów logów SMS');
assert(smsLogCleanupSqlSource.includes('device_id = null'), 'SQL nie kanonikalizuje zachowanego logu do poziomu montażu');
assert(releaseZipSource.includes('collectReleaseFiles'), 'scripts/release-zip.cjs nie zbiera jawnej listy plików');
assert(releaseZipSource.includes('createReleaseZip'), 'scripts/release-zip.cjs nie udostępnia createReleaseZip dla smoke testu');
assert(releaseZipSource.includes('playwright-report'), 'scripts/release-zip.cjs nie wyklucza playwright-report');
assert(releaseZipSource.includes('test-results'), 'scripts/release-zip.cjs nie wyklucza test-results');
assert(releaseZipSource.includes('excludedDirectoryNamePatterns'), 'scripts/release-zip.cjs nie ma wzorców wykluczania katalogów');
assert(releaseZipSource.includes('logs*'), 'scripts/release-zip.cjs nie wyklucza katalogów logs*');
assert(releaseZipSource.includes('*.log'), 'scripts/release-zip.cjs nie wyklucza plików *.log');
assert(releaseZipSource.includes('*.tmp'), 'scripts/release-zip.cjs nie wyklucza plików *.tmp');
assert(releaseZipSource.includes("'-@'"), 'scripts/release-zip.cjs nie pakuje jawnej listy przez zip -@');
assert(!releaseZipSource.includes("'-r'"), 'scripts/release-zip.cjs nadal używa zip -r');
assert(smokeReleaseZipSource.includes('node_modules'), 'test:smoke:release-zip nie tworzy fałszywego node_modules');
assert(smokeReleaseZipSource.includes('createReleaseZip'), 'test:smoke:release-zip nie uruchamia release-zip.cjs');
assert(smokeReleaseZipSource.includes('unzip'), 'test:smoke:release-zip nie sprawdza zawartości ZIP');
assert(smokeReleaseZipCleanSource.includes('logs735'), 'test:smoke:release-zip-clean nie sprawdza starych katalogów logs*');
assert(smokeReleaseZipCleanSource.includes('debug.log'), 'test:smoke:release-zip-clean nie sprawdza plików *.log');
assert(smokeReleaseZipCleanSource.includes('createReleaseZip'), 'test:smoke:release-zip-clean nie uruchamia release-zip.cjs');
assert(smokeJobDeviceTypeSwitchSource.includes('Single-split') && smokeJobDeviceTypeSwitchSource.includes('Multi-split'), 'test:smoke:job-device-type-switch nie pilnuje przełącznika single/multi');
assert(smokeJobDeviceTypeSwitchSource.includes('normalizeIndoorSerialPlaceholders'), 'test:smoke:job-device-type-switch nie pilnuje pustych pozycji JW w formularzu');
assert(smokeJobDeviceSpacesSource.includes('keepTypingSpaces'), 'test:smoke:job-device-spaces nie pilnuje spacji podczas edycji pól urządzenia');
assert(smokeJobDeviceSpacesSource.includes('Daikin Perfera 3,5 kW'), 'test:smoke:job-device-spaces nie pilnuje modelu urządzenia ze spacjami');
assert(smokeSupabaseGrantsSource.includes('create table') && smokeSupabaseGrantsSource.includes('hasGrant'), 'test:smoke:supabase-grants nie sprawdza CREATE TABLE i GRANT');
assert(smokeSupabaseGrantsSource.includes('enable row level security'), 'test:smoke:supabase-grants nie sprawdza RLS');
assert(supabaseGrantsAuditSource.includes('information_schema.role_table_grants'), 'supabase-grants-audit-wawis.sql nie sprawdza role_table_grants');
assert(supabaseGrantsAuditSource.includes('WZORZEC DLA KAŻDEJ NOWEJ TABELI'), 'supabase-grants-audit-wawis.sql nie zawiera wzorca dla nowych tabel');
assert(smokeCalendarWidthSource.includes('calendarDesktopWideSection'), 'test:smoke:calendar-width nie pilnuje szerokich sekcji kalendarza');
assert(smokeCalendarWidthSource.includes('min-width:1400px'), 'test:smoke:calendar-width nie pilnuje breakpointu 1400px');
assert(jobDetailsSource.includes('Wróć do kalendarza'), 'JobDetailsPanel nie zawiera przycisku Wróć do kalendarza');
assert(jobDetailsSource.includes('DesktopJobDeviceCards') && jobDetailsSource.includes('installationPhotos') && desktopJobDeviceCardsSource.includes('DesktopNameplateOcrButton'), 'Desktopowy panel nie wiąże odczytu wyłącznie z kartami tabliczek JZ/JW');
assert(desktopNameplateOcrComponentSource.includes('Odczytaj przez AI') && desktopNameplateOcrComponentSource.includes('Odczytaj kody') && desktopNameplateOcrComponentSource.includes('Zatwierdź i zapisz'), 'Desktopowy modal odczytu tabliczek nie ma wymaganych akcji administratora');
assert(!desktopNameplateOcrComponentSource.includes('Odczytaj nadruk OCR') && !desktopNameplateOcrComponentSource.includes('runLocalOcrRead'), 'Desktopowy modal nadal udostępnia lokalny OCR');
assert(desktopNameplateOcrComponentSource.includes('scanDesktopNameplateModelCode') && desktopNameplateOcrComponentSource.includes('Lokalny odczyt nadruku'), 'Niebieski przycisk nie uruchamia lokalnego odczytu modelu');
assert(desktopNameplateReaderUtilsSource.includes('fetchDesktopNameplateFile') && desktopNameplateReaderUtilsSource.includes('AbortController'), 'Desktopowy odczyt nie ma bezpiecznego pobierania zdjęcia');
assert(!desktopNameplateOcrSaveSource.includes("supabase.rpc('admin_sync_devices_from_jobs')") && !desktopNameplateOcrSaveSource.includes("supabase.rpc('admin_sync_device_from_job'") && desktopNameplateOcrSaveSource.includes('jobs_sync_device_after_change') && desktopNameplateOcrSaveSource.includes("from('jobs')"), 'Desktopowy zapis tabliczki nadal wykonuje zbędną synchronizację RPC zamiast polegać na triggerze jednego zlecenia');
assert(smokeDesktopNameplateOcrSource.includes('DesktopNameplateOcrButton') && smokeDesktopNameplateOcrSource.includes('Legacy local OCR action returned'), 'Test desktopowego odczytu nie pilnuje braku lokalnego OCR');
assert(smokeDesktopNameplateAutomaticFallbackSource.includes('5905567601132') && smokeDesktopNameplateAutomaticFallbackSource.includes('540V9839703A70010130182'), 'Test czytnika kodów nie pilnuje tabliczki RO35Xi R14');
assert(desktopNameplateBarcodeModuleSource.includes("source: 'local_ean13'") && desktopNameplateBarcodeModuleSource.includes("'universal_barcode'"), 'Czytnik tabliczek nie ma lokalnego EAN-13 lub uniwersalnego czytnika kodów');
assert(!desktopNameplateBarcodeModuleSource.includes('printed_ocr') && !desktopNameplateBarcodeModuleSource.includes('scanDesktopNameplateIdentifiers'), 'Czytnik kodów nadal zawiera fallback OCR');
assert(!desktopNameplateBarcodeModuleSource.includes('unpkg.com'), 'Czytnik tabliczek nadal zależy od starego UNPKG runtime');
assert(jobDetailsSource.includes('showReturnToCalendar'), 'JobDetailsPanel nie ma warunku showReturnToCalendar');
assert(mockSupabaseSource.includes('admin@wawis.test') && mockSupabaseSource.includes('pracownik@wawis.test'), 'Mock Supabase nie zawiera danych administratora i pracownika');
assert(mockSupabaseSource.includes('admin_get_sms_module_snapshot'), 'Mock Supabase nie obsługuje snapshotu SMS');
assert(playwrightConfigSource.includes('viewport: { width: 1440, height: 1000 }'), 'Playwright nie ma desktopowego viewportu 1440x1000');
assert(desktopE2eSource.includes('administrator loguje się') && desktopE2eSource.includes('pracownik loguje się'), 'E2E desktop nie sprawdza administratora i pracownika');
const mobileE2eSource = fs.readFileSync(mobileE2eSpecPath, 'utf8');
const mobilePhotoSyncHookSource = fs.readFileSync(mobilePhotoSyncHookPath, 'utf8');
assert(mobileE2eSource.includes("devices['iPhone 14']"), 'Mobilny E2E nie używa profilu iPhone 14');
assert(mobileE2eSource.includes('workerPage') && mobileE2eSource.includes('adminPage'), 'Mobilny E2E nie sprawdza dwóch sesji');
assert(mobileE2eSource.includes('setInputFiles') && mobileE2eSource.includes('Usunąć zdjęcie?'), 'Mobilny E2E nie sprawdza dodania i usunięcia zdjęcia');
assert(mobileE2eSource.includes('Klient Testowy Multi-Split') && mobileE2eSource.includes('toHaveCount(3)') && mobileE2eSource.includes('mock-job-005'), 'Mobilny E2E nie sprawdza trzech JW i zdjęcia testowego Multi-Split');
assert(mobileE2eSource.includes('Model JW 1') && mobileE2eSource.includes('Model JW 2 — poprawiony') && mobileE2eSource.includes('Model JW 3'), 'Mobilny E2E nie sprawdza osobnego modelu każdej jednostki Multi-Split');
assert(mobilePhotoSyncHookSource.includes('navigator.onLine') && mobilePhotoSyncHookSource.includes('effectiveType'), 'Wskaźnik nie sprawdza jakości połączenia');
assert(mobileNameplateCaptureSource.includes('capture="environment"'), 'Mobilna dokumentacja tabliczek nie otwiera tylnego aparatu');
assert(mobileNameplateCaptureSource.includes('nameplateCameraInput') && mobileNameplateCaptureSource.includes('nameplateGalleryInput'), 'Mobilna dokumentacja tabliczek nie rozdziela aparatu i galerii');
assert(!mobileNameplateCaptureSource.includes('navigator.mediaDevices?.getUserMedia'), 'Mobilna dokumentacja nadal uruchamia osadzony podgląd aparatu');
assert(!mobileJobFormModalSource.includes('serial-number-ocr') && !mobileJobFormModalSource.includes('SerialNumberScanner'), 'Formularz mobilny nadal zależy od OCR');
assert(!packageJson.dependencies?.['tesseract.js'] && !packageJson.dependencies?.['@zxing/browser'], 'Paczka mobilna nadal instaluje biblioteki OCR');
assert(mobileSerialE2eSource.includes('uproszczony kreator urządzeń bez OCR') && mobileSerialE2eSource.includes('Nie można zakończyć zlecenia') && mobileSerialE2eSource.includes('toBeDisabled') && mobileSerialE2eSource.includes('toBeEnabled'), 'E2E nie sprawdza kreatora, wymaganych tabliczek i blokady zakończenia');

verifyAutomaticDocInsertion(readme, changelog, appVersion);

if (requireZip) {
  const zipName = `klima-app-v${appVersion}.zip`;
  const zipPath = path.join(releasesDir, zipName);
  assert(fs.existsSync(zipPath), `Brak paczki release: ${zipName}`);
  const stats = fs.statSync(zipPath);
  assert(stats.isFile(), `Release ZIP nie jest plikiem: ${zipName}`);
  assert(stats.size > 0, `Release ZIP jest pusty: ${zipName}`);
  const zipListing = execFileSync('unzip', ['-l', zipPath], { encoding: 'utf8' });
  assert(!/node_modules\//.test(zipListing), `Release ZIP nadal zawiera node_modules: ${zipName}`);
  assert(!/dist\//.test(zipListing), `Release ZIP nadal zawiera dist: ${zipName}`);
  assert(!/supabase\/\.temp\//.test(zipListing), `Release ZIP nadal zawiera katalog supabase/.temp: ${zipName}`);
  assert(!/README-SMS-STAGE-[^\s]*/.test(zipListing), `Release ZIP nadal zawiera robocze README-SMS-STAGE-* : ${zipName}`);
  assert(!/README-START\.txt/.test(zipListing), `Release ZIP nadal zawiera zbędny README-START.txt: ${zipName}`);
  assert(!/(^|\n)\s*\d+\s+\d{2}-\d{2}-\d{4}\s+\d{2}:\d{2}\s+logs[^\s]*\//m.test(zipListing), `Release ZIP nadal zawiera katalog logs*: ${zipName}`);
  assert(!/(^|\n)\s*\d+\s+\d{2}-\d{2}-\d{4}\s+\d{2}:\d{2}\s+[^\s]+\.log\n/m.test(zipListing), `Release ZIP nadal zawiera plik .log: ${zipName}`);
  assert(!/(^|\n)\s*\d+\s+\d{2}-\d{2}-\d{4}\s+\d{2}:\d{2}\s+[^\s]+\.tmp\n/m.test(zipListing), `Release ZIP nadal zawiera plik .tmp: ${zipName}`);
  assert(!/(^|\n)\s*\d+\s+\d{2}-\d{2}-\d{4}\s+\d{2}:\d{2}\s+npx\n/m.test(zipListing), `Release ZIP nadal zawiera pusty plik npx: ${zipName}`);
}

console.log(`Release verification OK for version ${appVersion}${requireZip ? ' (zip verified)' : ''}`);
process.exit(0);
